project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands on Exercises/Hands_on_ex1/hands-on-ex1.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

