project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1: Geospatial Data Science with R"
            href: "hands-on-exercises/Hands-on_Ex01/hands-on-ex1.html"
          - text: "Hands-on Exercise 2: Thematic Mapping and GeoVisualisation with R"
            href: "hands-on-exercises/Hands-on_Ex02/hands-on-ex2.html"
          - text: "Hands-on Exercise 3: 1st Order SPAA"
            href: "hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p1/hands-on-ex3_p1.html"
          - text: "Hands-on Exercise 3: 2nd Order SPAA"
            href: "hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p2/hands-on-ex3_p2.html"
          - text: "Hands-on Exercise 4: ICE4"
            href: "in-class_exercises/in-class_ex04/in-class_Ex04.html"
          - text: "Hands-on Exercise 5: Spatial Weights and Applications"
            href: "hands-on-exercises/Hands-on_Ex05/hands-on-ex5.html"
          - text: "Hands-on Exercise 6: Global Measures of Spatial Autocorrelation"
            href: "hands-on-exercises/Hands-on_Ex06/hands-on-ex6_global/hands-on-ex6_global.html"
          - text: "Hands-on Exercise 6: Local Measures of Spatial Autocorrelation"
            href: "hands-on-exercises/Hands-on_Ex06/hands-on-ex6_local/hands-on-ex6_local.html"
          - text: "Hands-on Exercise 7 & 8: Geographical Segmentation with Spatially Constrained Clustering Techniques"
            href: "hands-on-exercises/Hands-on_Ex07n8/hands-on-ex7n8.html"
      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 1"
            href: "in-class_exercises/in-class_ex01/in-class_Ex01-v2.html"
          - text: "In-class Exercise 2"
            href: "in-class_exercises/in-class_ex02/in-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "in-class_exercises/in-class_ex03/in-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "in-class_exercises/in-class_ex04/in-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "in-class_exercises/in-class_ex05/in-class_Ex05.html"
          - text: "In-class Exercise 6"
            href: "in-class_exercises/in-class_ex06/in-class_Ex06.html"
      - text: "Take-home Exercises"
        menu:
          - text: "Take-home Exercise 1"
            href: "take-home_exercises/take-home_ex01/take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "take-home_exercises/take-home_ex02/take-home_Ex02.html"
        
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

