project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "hands-on-exercises/Hands-on_Ex01/hands-on-ex1.html"
          - text: "Hands-on Exercise 2"
            href: "hands-on-exercises/Hands-on_Ex02/hands-on-ex2.html"
          - text: "Hands-on Exercise 3: 1st Order SPAA"
            href: "hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p1/hands-on-ex3_p1.html"
          - text: "Hands-on Exercise 3: 2nd Order SPAA"
            href: "hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p2/hands-on-ex3_p2.html"
      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 1"
            href: "in-class_exercises/in-class_ex01/in-class_Ex01-v2.html"
          - text: "In-class Exercise 2"
            href: "in-class_exercises/in-class_ex02/in-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "in-class_exercises/in-class_ex03/in-class_Ex03.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

