<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcus Jaeson Yeo">
<meta name="dcterms.date" content="2024-10-27">

<title>IS415-GAA - Take-Home Exercise 3: Prototyping Modules for Geospatial Analytics Shiny Application</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex01/hands-on-ex1.html">
 <span class="dropdown-text">Hands-on Exercise 1: Geospatial Data Science with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex02/hands-on-ex2.html">
 <span class="dropdown-text">Hands-on Exercise 2: Thematic Mapping and GeoVisualisation with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p1/hands-on-ex3_p1.html">
 <span class="dropdown-text">Hands-on Exercise 3: 1st Order SPAA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p2/hands-on-ex3_p2.html">
 <span class="dropdown-text">Hands-on Exercise 3: 2nd Order SPAA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex04/in-class_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4: ICE4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex05/hands-on-ex5.html">
 <span class="dropdown-text">Hands-on Exercise 5: Spatial Weights and Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex06/hands-on-ex6_global/hands-on-ex6_global.html">
 <span class="dropdown-text">Hands-on Exercise 6: Global Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex06/hands-on-ex6_local/hands-on-ex6_local.html">
 <span class="dropdown-text">Hands-on Exercise 6: Local Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex07n8/hands-on-ex7n8.html">
 <span class="dropdown-text">Hands-on Exercise 7 &amp; 8: Geographical Segmentation with Spatially Constrained Clustering Techniques</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex09/hands-on-ex9.html">
 <span class="dropdown-text">Hands-on Exercise 9: Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex01/in-class_Ex01-v2.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex02/in-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex03/in-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex04/in-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex05/in-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex06/in-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex09/in-class_Ex09.html">
 <span class="dropdown-text">In-class Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex10/in-class_Ex10.html">
 <span class="dropdown-text">In-class Exercise 10</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../take-home_exercises/take-home_ex01/take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../take-home_exercises/take-home_ex02/take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../take-home_exercises/take-home_ex03/take-home_Ex03.html">
 <span class="dropdown-text">Take-home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">1.0 Overview</a>
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">1.1 Objectives</a></li>
  <li><a href="#focus" id="toc-focus" class="nav-link" data-scroll-target="#focus">1.2 Focus</a></li>
  <li><a href="#prototyping-for-shiny-application" id="toc-prototyping-for-shiny-application" class="nav-link" data-scroll-target="#prototyping-for-shiny-application">1.3 Prototyping for Shiny Application</a></li>
  </ul></li>
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link" data-scroll-target="#load-packages">2.0 Load packages</a></li>
  <li><a href="#importing-data-and-data-wrangling" id="toc-importing-data-and-data-wrangling" class="nav-link" data-scroll-target="#importing-data-and-data-wrangling">3.0 Importing Data and Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#raw-data" id="toc-raw-data" class="nav-link" data-scroll-target="#raw-data">3.1 Raw Data</a></li>
  <li><a href="#geospatial-wrangling" id="toc-geospatial-wrangling" class="nav-link" data-scroll-target="#geospatial-wrangling">3.2 Geospatial Wrangling</a></li>
  <li><a href="#aspatial-wrangling" id="toc-aspatial-wrangling" class="nav-link" data-scroll-target="#aspatial-wrangling">3.3 Aspatial Wrangling</a></li>
  <li><a href="#combine-data" id="toc-combine-data" class="nav-link" data-scroll-target="#combine-data">3.4 Combine Data</a></li>
  <li><a href="#pivot-longer-to-reduce-number-of-rows" id="toc-pivot-longer-to-reduce-number-of-rows" class="nav-link" data-scroll-target="#pivot-longer-to-reduce-number-of-rows">3.5 Pivot longer to reduce number of rows</a></li>
  <li><a href="#projection-transformation" id="toc-projection-transformation" class="nav-link" data-scroll-target="#projection-transformation">3.6 Projection Transformation</a></li>
  <li><a href="#visualisation" id="toc-visualisation" class="nav-link" data-scroll-target="#visualisation">3.7 Visualisation</a></li>
  <li><a href="#writeread-rds" id="toc-writeread-rds" class="nav-link" data-scroll-target="#writeread-rds">3.8 Write/Read rds</a></li>
  </ul></li>
  <li><a href="#shiny-visualisation-shiny-storyboard" id="toc-shiny-visualisation-shiny-storyboard" class="nav-link" data-scroll-target="#shiny-visualisation-shiny-storyboard">4.0 Shiny Visualisation / Shiny Storyboard</a></li>
  <li><a href="#spatial-weights-and-applications" id="toc-spatial-weights-and-applications" class="nav-link" data-scroll-target="#spatial-weights-and-applications">6.0 Spatial Weights and Applications</a></li>
  <li><a href="#global-measures-of-spatial-autocorrelation" id="toc-global-measures-of-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-measures-of-spatial-autocorrelation">6.0 Global Measures of Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#configuring-and-binding-coordinates" id="toc-configuring-and-binding-coordinates" class="nav-link" data-scroll-target="#configuring-and-binding-coordinates">6.1 Configuring and Binding coordinates</a></li>
  <li><a href="#computing-distance-based-neighbours" id="toc-computing-distance-based-neighbours" class="nav-link" data-scroll-target="#computing-distance-based-neighbours">6.2 Computing distance-based neighbours</a></li>
  <li><a href="#attempting-fixed-distance" id="toc-attempting-fixed-distance" class="nav-link" data-scroll-target="#attempting-fixed-distance">6.2.1 Attempting Fixed Distance</a></li>
  <li><a href="#attempting-adaptive-distance" id="toc-attempting-adaptive-distance" class="nav-link" data-scroll-target="#attempting-adaptive-distance">6.2.2 Attempting Adaptive Distance</a></li>
  <li><a href="#global-moran-i-access-spatial-autocorrelation-using-adaptive-distance" id="toc-global-moran-i-access-spatial-autocorrelation-using-adaptive-distance" class="nav-link" data-scroll-target="#global-moran-i-access-spatial-autocorrelation-using-adaptive-distance">6.2.3 Global Moran I: Access Spatial Autocorrelation using Adaptive Distance</a></li>
  <li><a href="#spatial-correlogram" id="toc-spatial-correlogram" class="nav-link" data-scroll-target="#spatial-correlogram">6.3 Spatial Correlogram</a></li>
  </ul></li>
  <li><a href="#local-measures-of-spatial-autocorrelation" id="toc-local-measures-of-spatial-autocorrelation" class="nav-link" data-scroll-target="#local-measures-of-spatial-autocorrelation">7.0 Local Measures of Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#adaptive-distance-weight-matrix" id="toc-adaptive-distance-weight-matrix" class="nav-link" data-scroll-target="#adaptive-distance-weight-matrix">7.1 Adaptive Distance Weight Matrix</a></li>
  <li><a href="#lisa" id="toc-lisa" class="nav-link" data-scroll-target="#lisa">7.2 LISA</a></li>
  <li><a href="#computing-local-morans-i" id="toc-computing-local-morans-i" class="nav-link" data-scroll-target="#computing-local-morans-i">7.2.1 Computing Local Moran’s I</a></li>
  <li><a href="#mapping-local-morans-i" id="toc-mapping-local-morans-i" class="nav-link" data-scroll-target="#mapping-local-morans-i">7.2.2 Mapping local Moran’s I</a></li>
  <li><a href="#creating-lisa-cluster-map" id="toc-creating-lisa-cluster-map" class="nav-link" data-scroll-target="#creating-lisa-cluster-map">7.3 Creating LISA Cluster Map</a></li>
  <li><a href="#plotting-moran-scatterplot" id="toc-plotting-moran-scatterplot" class="nav-link" data-scroll-target="#plotting-moran-scatterplot">7.3.1 Plotting Moran scatterplot</a></li>
  <li><a href="#plotting-moran-scatterplot-with-standardized-variable" id="toc-plotting-moran-scatterplot-with-standardized-variable" class="nav-link" data-scroll-target="#plotting-moran-scatterplot-with-standardized-variable">7.3.2 Plotting Moran scatterplot with standardized variable</a></li>
  <li><a href="#lisa-map-classes" id="toc-lisa-map-classes" class="nav-link" data-scroll-target="#lisa-map-classes">7.3.3 LISA map classes</a></li>
  <li><a href="#plotting-lisa-map" id="toc-plotting-lisa-map" class="nav-link" data-scroll-target="#plotting-lisa-map">7.3.4 <strong>Plotting LISA map</strong></a></li>
  <li><a href="#computing-gi-statistics-total-cases-over-the-years" id="toc-computing-gi-statistics-total-cases-over-the-years" class="nav-link" data-scroll-target="#computing-gi-statistics-total-cases-over-the-years">7.4 Computing Gi Statistics (total cases over the years)</a></li>
  <li><a href="#gi-statistics-for-adaptive-distance" id="toc-gi-statistics-for-adaptive-distance" class="nav-link" data-scroll-target="#gi-statistics-for-adaptive-distance">7.4.1 Gi statistics for adaptive distance</a></li>
  <li><a href="#plotting-and-mapping-gi-values-with-adaptive-distance-weights" id="toc-plotting-and-mapping-gi-values-with-adaptive-distance-weights" class="nav-link" data-scroll-target="#plotting-and-mapping-gi-values-with-adaptive-distance-weights">7.4.2 Plotting and Mapping Gi values with adaptive distance weights</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-Home Exercise 3: Prototyping Modules for Geospatial Analytics Shiny Application</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marcus Jaeson Yeo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 27, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 3, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">1.0 Overview</h2>
<section id="objectives" class="level3">
<h3 class="anchored" data-anchor-id="objectives">1.1 Objectives</h3>
<ul>
<li><p>To evaluate and determine the necessary R packages needed for your Shiny application are supported in R CRAN,</p></li>
<li><p>To prepare and test the specific R codes can be run and returned the correct output as expected,</p></li>
<li><p>To determine the parameters and outputs that will be exposed on the Shiny applications, and</p></li>
<li><p>To select the appropriate Shiny UI components for exposing the parameters determine above.</p></li>
</ul>
</section>
<section id="focus" class="level3">
<h3 class="anchored" data-anchor-id="focus">1.2 Focus</h3>
<p>The focus within this Take-Home Exercise, as part of the group project, would be our geographical and aspatial target on:</p>
<ul>
<li><p>districts within East Malaysia (Sabah, Sarawak, W.P Labuan)</p>
<ul>
<li>[Profile of East Malaysia](https://www.mavcom.my/en/industry/public-service-obligations/profile-of-east-malaysia/#:~:text=East%20Malaysia%20(consisting%20of%20the,by%20the%20South%20China%20Sea.)</li>
</ul></li>
<li><p>category: assault</p></li>
<li><p>type: rape</p></li>
</ul>
<p>We will be discovering the <strong>rape</strong> trends that take place within the <strong>districts</strong> of <strong>East Malaysia</strong>, across the years <strong>2020-2023</strong>, discovering the emerging hot spots and cold spots, outliers, as well as determine the spatial autocorrelation within these districts.</p>
</section>
<section id="prototyping-for-shiny-application" class="level3">
<h3 class="anchored" data-anchor-id="prototyping-for-shiny-application">1.3 Prototyping for Shiny Application</h3>
</section>
</section>
<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">2.0 Load packages</h2>
<ul>
<li><p>sf</p></li>
<li><p>tmap</p></li>
<li><p>tidyverse</p></li>
<li><p>spdep</p></li>
<li><p>sfdep</p></li>
<li><p>dplyr</p></li>
<li><p>tidyr</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tmap, tidyverse, spdep, sfdep, dplyr, tidyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-data-and-data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="importing-data-and-data-wrangling">3.0 Importing Data and Data Wrangling</h2>
<section id="raw-data" class="level3">
<h3 class="anchored" data-anchor-id="raw-data">3.1 Raw Data</h3>
<ul>
<li>geospatial</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>msia_adm2 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">'data/geospatial/'</span>, <span class="at">layer =</span> <span class="st">'mys_admbnda_adm2_unhcr_20210211'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `mys_admbnda_adm2_unhcr_20210211' from data source 
  `C:\marcus159260\IS415-GAA\take-home_exercises\take-home_ex03\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 144 features and 14 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 99.64072 ymin: 0.855001 xmax: 119.2697 ymax: 7.380556
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># msia_adm2_shp &lt;- st_read(dsn = 'data/geospatial/mys_admbnda_adm1_unhcr_20210211.shp')</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>aspatial</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>msia_sf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'data/aspatial/crime_district.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 19152 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): state, district, category, type
dbl  (1): crimes
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="geospatial-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="geospatial-wrangling">3.2 Geospatial Wrangling</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msia_adm2[<span class="st">"ADM2_EN"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Upon plotting out the shapefile of Admin level 2, we can see that it takes both East and West Malaysia. However, we only want East Malaysia (Sabah, Sarawak).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(msia_adm2<span class="sc">$</span>ADM1_EN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Johor"             "Kedah"             "Kelantan"         
 [4] "W.P. Kuala Lumpur" "W.P. Labuan"       "Melaka"           
 [7] "Negeri Sembilan"   "Pahang"            "Perak"            
[10] "Perlis"            "Pulau Pinang"      "Sabah"            
[13] "Sarawak"           "Terengganu"        "W.P. Putrajaya"   
[16] "Selangor"         </code></pre>
</div>
</div>
<p>We will convert all to lowercase and do necessary trimming for appropriate left-join later to combine with our working data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>msia_adm2 <span class="ot">&lt;-</span> msia_adm2 <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ADM1_EN =</span> <span class="fu">str_to_lower</span>(ADM1_EN),  </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ADM1_EN =</span> <span class="fu">str_trim</span>(ADM1_EN)) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ADM2_EN =</span> <span class="fu">str_to_lower</span>(ADM2_EN),  </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">ADM2_EN =</span> <span class="fu">str_trim</span>(ADM2_EN)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we separate East Malaysia, only filtering “sabah”, “sarawak”, “w.p. labuan” regions. We will select only the necessary columns: ADM1_EN, ADM2_EN, geometry.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>msia_adm2_east <span class="ot">&lt;-</span> msia_adm2 <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"sabah"</span>, <span class="st">"sarawak"</span>, <span class="st">"w.p. labuan"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"ADM1_EN"</span>, <span class="st">"ADM2_EN"</span>, <span class="st">"geometry"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>msia_adm2_east</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 57 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 109.5379 ymin: 0.855001 xmax: 119.2697 ymax: 7.380556
Geodetic CRS:  WGS 84
First 10 features:
       ADM1_EN       ADM2_EN                       geometry
1  w.p. labuan   w.p. labuan MULTIPOLYGON (((115.2528 5....
2        sabah      beaufort MULTIPOLYGON (((115.58 5.21...
3        sabah       beluran MULTIPOLYGON (((117.7142 6....
4        sabah      keningau MULTIPOLYGON (((116.0938 4....
5        sabah  kinabatangan MULTIPOLYGON (((119.2474 5....
6        sabah    kota belud MULTIPOLYGON (((116.61 6.66...
7        sabah kota kinabalu MULTIPOLYGON (((116.3009 5....
8        sabah   kota marudu MULTIPOLYGON (((116.3408 6....
9        sabah   kuala penyu MULTIPOLYGON (((115.3682 5....
10       sabah         kudat MULTIPOLYGON (((116.6292 6....</code></pre>
</div>
</div>
<p>Now, when we plot back, we can see that only East Malaysia polygon shapes are filtered.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msia_adm2_east)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>3 states, 57 districts</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(msia_adm2_east<span class="sc">$</span>ADM1_EN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "w.p. labuan" "sabah"       "sarawak"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(msia_adm2_east<span class="sc">$</span>ADM2_EN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "w.p. labuan"   "beaufort"      "beluran"       "keningau"     
 [5] "kinabatangan"  "kota belud"    "kota kinabalu" "kota marudu"  
 [9] "kuala penyu"   "kudat"         "kunak"         "lahad datu"   
[13] "nabawan"       "papar"         "penampang"     "pitas"        
[17] "putatan"       "ranau"         "sandakan"      "semporna"     
[21] "sipitang"      "tambunan"      "tawau"         "tenom"        
[25] "tongod"        "tuaran"        "asajaya"       "bau"          
[29] "belaga"        "betong"        "bintulu"       "dalat"        
[33] "daro"          "julau"         "kanowit"       "kapit"        
[37] "kuching"       "lawas"         "limbang"       "lubok antu"   
[41] "lundu"         "marudi"        "matu"          "meradong"     
[45] "miri"          "mukah"         "pakan"         "samarahan"    
[49] "saratok"       "sarikei"       "selangau"      "serian"       
[53] "sibu"          "simunjan"      "song"          "sri aman"     
[57] "tatau"        </code></pre>
</div>
</div>
</section>
<section id="aspatial-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="aspatial-wrangling">3.3 Aspatial Wrangling</h3>
<ul>
<li>Likewise, we do filtering and wrangling on the <strong>state</strong> and <strong>district, category: assault</strong> and <strong>type: rape.</strong></li>
</ul>
<p>First, we see the columns and rows available in sf using glimpse.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(msia_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 19,152
Columns: 6
$ state    &lt;chr&gt; "Malaysia", "Malaysia", "Malaysia", "Malaysia", "Malaysia", "…
$ district &lt;chr&gt; "All", "All", "All", "All", "All", "All", "All", "All", "All"…
$ category &lt;chr&gt; "assault", "assault", "assault", "assault", "assault", "assau…
$ type     &lt;chr&gt; "all", "all", "all", "all", "all", "all", "all", "all", "caus…
$ date     &lt;date&gt; 2016-01-01, 2017-01-01, 2018-01-01, 2019-01-01, 2020-01-01, …
$ crimes   &lt;dbl&gt; 22327, 21366, 16902, 16489, 13279, 11495, 10348, 10453, 5531,…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>msia_sf <span class="ot">&lt;-</span> msia_sf <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">str_to_lower</span>(state),  </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">state =</span> <span class="fu">str_trim</span>(state)) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">district =</span> <span class="fu">str_to_lower</span>(district),  </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">district =</span> <span class="fu">str_trim</span>(district)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we separate East Malaysia, only filtering “sabah” and “sarawak” regions. We will select only the necessary columns: ADM1_EN, ADM2_EN, geometry.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>msia_sf_east <span class="ot">&lt;-</span> msia_sf <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"sabah"</span>, <span class="st">"sarawak"</span>), </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         category <span class="sc">==</span> <span class="st">"assault"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(type <span class="sc">!=</span> <span class="st">"all"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>msia_sf_east</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,800 × 6
   state district category type           date       crimes
   &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;          &lt;date&gt;      &lt;dbl&gt;
 1 sabah all      assault  causing_injury 2016-01-01    213
 2 sabah all      assault  causing_injury 2017-01-01    230
 3 sabah all      assault  causing_injury 2018-01-01    216
 4 sabah all      assault  causing_injury 2019-01-01    221
 5 sabah all      assault  causing_injury 2020-01-01    176
 6 sabah all      assault  causing_injury 2021-01-01    148
 7 sabah all      assault  causing_injury 2022-01-01    169
 8 sabah all      assault  causing_injury 2023-01-01    176
 9 sabah all      assault  murder         2016-01-01     60
10 sabah all      assault  murder         2017-01-01     36
# ℹ 2,790 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(msia_sf_east<span class="sc">$</span>type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "causing_injury"       "murder"               "rape"                
[4] "robbery_gang_armed"   "robbery_gang_unarmed" "robbery_solo_armed"  
[7] "robbery_solo_unarmed"</code></pre>
</div>
</div>
<p>We see that we do not need the “all” results for districts and we need to do a sorting by their date of occurrence in ascending order.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>msia_sf_east <span class="ot">&lt;-</span> msia_sf_east <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(<span class="fu">ymd</span>(date)) <span class="sc">&gt;=</span> <span class="dv">2020</span> <span class="sc">&amp;</span> <span class="fu">year</span>(<span class="fu">ymd</span>(date)) <span class="sc">&lt;=</span> <span class="dv">2023</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(district <span class="sc">!=</span> <span class="st">"all"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><u><strong>Dealing with Inconsistencies and mispelled districts</strong></u></p>
<ul>
<li><p><strong>“kota kinabatangan”</strong> in <code>msia_sf_east$district</code> should be <strong>“kinabatangan”</strong> as in <code>msia_adm2_east$ADM2_EN</code>.</p>
<ul>
<li>rename “kota kinbatangan” to “kinabatangan” in <code>msia_sf_east$district</code></li>
</ul></li>
<li><p><strong>“matu daro”</strong> in <code>msia_sf_east$district</code> might represent two separate districts: <strong>“matu”</strong> and <strong>“daro”</strong> in <code>msia_adm2_east$ADM2_EN</code>.</p>
<ul>
<li>will split first half of the (matu daro) rows take matu, second half take daro, impute with the average of the crimes of matu daro rows in <code>msia_sf_east$district</code></li>
</ul></li>
<li><p><strong>“padawan”</strong> in <code>msia_sf_east$district</code> does not appear in <code>msia_adm2_east$ADM2_EN</code>, as Padawan is often categorized within <strong>“kuching”</strong> but may need verification as a separate district.</p>
<ul>
<li>follow shapefile, so we rename “<strong>padawan”</strong> in <code>msia_sf_east$district</code> to”<strong>kuching”</strong></li>
</ul></li>
<li><p><strong>“w.p. labuan”</strong> appears in <code>msia_sf_east$district</code> but is not listed in <code>msia_adm2_east$ADM2_EN</code>, which could be due to handling federal territories separately.</p>
<ul>
<li>Update “w.p. labuan” as a separate state and district in <code>msia_sf_east$district</code></li>
</ul></li>
<li><p><strong>“kota samarahan”</strong> in <code>msia_sf_east$district</code> should be <strong>“samarahan”</strong> as in <code>msia_adm2_east$ADM2_EN</code>.</p>
<ul>
<li>rename <strong>“kota samarahan”</strong> to <strong>“samarahan”</strong> in <code>msia_sf_east$district</code></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>msia_sf_east_dealt <span class="ot">&lt;-</span> msia_sf_east <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">district =</span> <span class="fu">gsub</span>(<span class="st">"^kota kinabatangan$"</span>, <span class="st">"kinabatangan"</span>, district),  <span class="co"># Rename "kota kinbatangan" to "kinabatangan"</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">district =</span> <span class="fu">gsub</span>(<span class="st">"^padawan$"</span>, <span class="st">"kuching"</span>, district),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">district =</span> <span class="fu">gsub</span>(<span class="st">"^kota samarahan$"</span>, <span class="st">"samarahan"</span>, district)) <span class="sc">%&gt;%</span> <span class="co">#rename "padawan" to "kuching" </span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Update "w.p. labuan" as a separate state and district</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">if_else</span>(state <span class="sc">==</span> <span class="st">"sabah"</span> <span class="sc">&amp;</span> district <span class="sc">==</span> <span class="st">"w.p. labuan"</span>, <span class="st">"w.p. labuan"</span>, state),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">district =</span> <span class="fu">if_else</span>(state <span class="sc">==</span> <span class="st">"w.p. labuan"</span> <span class="sc">&amp;</span> district <span class="sc">==</span> <span class="st">"w.p. labuan"</span>, <span class="st">"w.p. labuan"</span>, district)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>impute average for matu daro, and split matu and daro</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>split_matu_daro <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filter rows for "matu daro"</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  matu_daro_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(district <span class="sc">==</span> <span class="st">"matu daro"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(matu_daro_data)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate the average crimes for "matu" and "daro" from all entries</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  total_crimes <span class="ot">&lt;-</span> <span class="fu">sum</span>(matu_daro_data<span class="sc">$</span>crimes) <span class="co"># Total crimes</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  num_entries <span class="ot">&lt;-</span> <span class="fu">nrow</span>(matu_daro_data)        <span class="co"># Number of entries</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Average for both "matu" and "daro"</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  average_crime <span class="ot">&lt;-</span> <span class="fu">round</span>(total_crimes <span class="sc">/</span> num_entries) <span class="co"># Round to nearest whole number</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(average_crime)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>   <span class="co"># Calculate midpoint for splitting the data</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  midpoint <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(num_entries <span class="sc">/</span> <span class="dv">2</span>) <span class="co"># Use ceiling to handle odd numbers</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create new entries for "matu" and "daro"</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  new_entries <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(matu_daro_data[<span class="dv">1</span><span class="sc">:</span>midpoint, ], <span class="at">district =</span> <span class="st">"matu"</span>, <span class="at">crimes =</span> average_crime), <span class="co"># First half for "matu"</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(matu_daro_data[(midpoint <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>num_entries, ], <span class="at">district =</span> <span class="st">"daro"</span>, <span class="at">crimes =</span> average_crime) <span class="co"># Second half for "daro"</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print new entries for debugging</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(new_entries)</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(new_entries)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>matu_daro_split <span class="ot">&lt;-</span> <span class="fu">split_matu_daro</span>(msia_sf_east_dealt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 28 × 6
   state   district  category type                 date       crimes
   &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;                &lt;date&gt;      &lt;dbl&gt;
 1 sarawak matu daro assault  causing_injury       2020-01-01      0
 2 sarawak matu daro assault  murder               2020-01-01      0
 3 sarawak matu daro assault  rape                 2020-01-01      1
 4 sarawak matu daro assault  robbery_gang_armed   2020-01-01      0
 5 sarawak matu daro assault  robbery_gang_unarmed 2020-01-01      0
 6 sarawak matu daro assault  robbery_solo_armed   2020-01-01      0
 7 sarawak matu daro assault  robbery_solo_unarmed 2020-01-01      0
 8 sarawak matu daro assault  causing_injury       2021-01-01      0
 9 sarawak matu daro assault  murder               2021-01-01      0
10 sarawak matu daro assault  rape                 2021-01-01      1
# ℹ 18 more rows
[1] 0
# A tibble: 28 × 6
   state   district category type                 date       crimes
   &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;                &lt;date&gt;      &lt;dbl&gt;
 1 sarawak matu     assault  causing_injury       2020-01-01      0
 2 sarawak matu     assault  murder               2020-01-01      0
 3 sarawak matu     assault  rape                 2020-01-01      0
 4 sarawak matu     assault  robbery_gang_armed   2020-01-01      0
 5 sarawak matu     assault  robbery_gang_unarmed 2020-01-01      0
 6 sarawak matu     assault  robbery_solo_armed   2020-01-01      0
 7 sarawak matu     assault  robbery_solo_unarmed 2020-01-01      0
 8 sarawak matu     assault  causing_injury       2021-01-01      0
 9 sarawak matu     assault  murder               2021-01-01      0
10 sarawak matu     assault  rape                 2021-01-01      0
# ℹ 18 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the new entries with the existing data, removing old "matu daro" entries</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>msia_sf_east_final <span class="ot">&lt;-</span> msia_sf_east_dealt <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(district <span class="sc">!=</span> <span class="st">"matu daro"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(matu_daro_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>3 states, 48 districts</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(msia_sf_east_final<span class="sc">$</span>state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sabah"       "w.p. labuan" "sarawak"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(msia_sf_east_final<span class="sc">$</span>district)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "beaufort"      "beluran"       "keningau"      "kota belud"   
 [5] "kota kinabalu" "kinabatangan"  "kota marudu"   "kudat"        
 [9] "kunak"         "lahad datu"    "papar"         "penampang"    
[13] "ranau"         "sandakan"      "semporna"      "sipitang"     
[17] "tawau"         "tenom"         "tuaran"        "w.p. labuan"  
[21] "bau"           "belaga"        "betong"        "bintulu"      
[25] "dalat"         "julau"         "kanowit"       "kapit"        
[29] "samarahan"     "kuching"       "lawas"         "limbang"      
[33] "lubok antu"    "lundu"         "marudi"        "meradong"     
[37] "miri"          "mukah"         "saratok"       "sarikei"      
[41] "serian"        "sibu"          "simunjan"      "song"         
[45] "sri aman"      "tatau"         "matu"          "daro"         </code></pre>
</div>
</div>
</section>
<section id="combine-data" class="level3">
<h3 class="anchored" data-anchor-id="combine-data">3.4 Combine Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>msia_left_join <span class="ot">&lt;-</span> msia_adm2_east <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(msia_sf_east_final, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ADM1_EN"</span> <span class="ot">=</span> <span class="st">"state"</span>, <span class="st">"ADM2_EN"</span> <span class="ot">=</span> <span class="st">"district"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> msia_left_join <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(crimes)) <span class="co"># Replace 'crimes' with the relevant column(s) you want to check</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 9 features and 6 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 110.4736 ymin: 1.519756 xmax: 117.5625 ymax: 7.013332
Geodetic CRS:  WGS 84
  ADM1_EN     ADM2_EN category type date crimes                       geometry
1   sabah kuala penyu     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((115.3682 5....
2   sabah     nabawan     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((115.8903 4....
3   sabah       pitas     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((116.9781 6....
4   sabah     putatan     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((116.0662 5....
5   sabah    tambunan     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((116.552 5.5...
6   sabah      tongod     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((117.5155 4....
7 sarawak     asajaya     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((110.664 1.5...
8 sarawak       pakan     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((111.7907 1....
9 sarawak    selangau     &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     NA MULTIPOLYGON (((112.6285 2....</code></pre>
</div>
</div>
<p>After left-joining, we see that these are the columns that are not present in our working data but are present in our boundary data, we thus have no choice but to drop them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>msia_left_join <span class="ot">&lt;-</span> msia_left_join <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(crimes)) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">4</span><span class="sc">:</span><span class="dv">7</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(msia_left_join, <span class="st">"data/rds/msia_left_join.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pivot-longer-to-reduce-number-of-rows" class="level3">
<h3 class="anchored" data-anchor-id="pivot-longer-to-reduce-number-of-rows">3.5 Pivot longer to reduce number of rows</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>msia_total_crimes <span class="ot">&lt;-</span> msia_left_join <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ensure 'date' is of Date type, if not already</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extract year from the date</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Group by ADM1_EN, ADM2_EN, geometry, and type, then summarize crimes across all years</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ADM1_EN, ADM2_EN, geometry, type) <span class="sc">%&gt;%</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_type_crimes =</span> <span class="fu">sum</span>(crimes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Pivot wider to create columns for each crime type across all years</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> type,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> total_type_crimes,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_prefix =</span> <span class="st">"total_crimes_"</span>,</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fill =</span> <span class="fu">list</span>(<span class="at">total_type_crimes =</span> <span class="dv">0</span>)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add a total_crimes column summing across all types for each district</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_crimes =</span> <span class="fu">sum</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"total_crimes_"</span>)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Keep ADM1_EN, ADM2_EN, and geometry as required, and reorder columns</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM2_EN, ADM1_EN, geometry, total_crimes, <span class="fu">everything</span>())</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a><span class="co"># View the resulting dataset</span></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(msia_total_crimes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 48 features and 10 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 109.5379 ymin: 0.855001 xmax: 119.2697 ymax: 7.380556
Geodetic CRS:  WGS 84
# A tibble: 48 × 11
   ADM2_EN ADM1_EN                  geometry total_crimes total_crimes_causing…¹
   &lt;chr&gt;   &lt;chr&gt;          &lt;MULTIPOLYGON [°]&gt;        &lt;dbl&gt;                  &lt;dbl&gt;
 1 beaufo… sabah   (((115.58 5.213697, 115.…           39                     15
 2 beluran sabah   (((117.7142 6.260833, 11…           72                     23
 3 kening… sabah   (((116.0938 4.861981, 11…           93                     22
 4 kinaba… sabah   (((119.2474 5.26962, 118…           56                     25
 5 kota b… sabah   (((116.61 6.666111, 116.…           52                     15
 6 kota k… sabah   (((116.3009 5.85547, 116…          405                    153
 7 kota m… sabah   (((116.3408 6.401667, 11…           49                      9
 8 kudat   sabah   (((116.6292 6.688926, 11…           42                     18
 9 kunak   sabah   (((118.1334 4.862195, 11…           27                      8
10 lahad … sabah   (((117.746 4.758972, 117…          116                     32
# ℹ 38 more rows
# ℹ abbreviated name: ¹​total_crimes_causing_injury
# ℹ 6 more variables: total_crimes_murder &lt;dbl&gt;, total_crimes_rape &lt;dbl&gt;,
#   total_crimes_robbery_gang_armed &lt;dbl&gt;,
#   total_crimes_robbery_gang_unarmed &lt;dbl&gt;,
#   total_crimes_robbery_solo_armed &lt;dbl&gt;,
#   total_crimes_robbery_solo_unarmed &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>msia_left_join_pivot <span class="ot">&lt;-</span> msia_left_join <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ensure 'date' is of Date type, if not already</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extract year from the date</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Group by the necessary columns and summarize</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ADM1_EN, ADM2_EN, geometry, type, year) <span class="sc">%&gt;%</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Summarize the crimes for each group, summing them up</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">crimes =</span> <span class="fu">sum</span>(crimes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Pivot wider to create crime columns for each year</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># names_from = year, </span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> <span class="fu">c</span>(type, year),</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> crimes,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_prefix =</span> <span class="st">"crimes_"</span>,</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># names_prefix = "crimes_",</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fill =</span> <span class="fu">list</span>(<span class="at">crimes =</span> <span class="cn">NULL</span>)  <span class="co"># Fill NA values with NULL</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a><span class="co"># View the resulting dataset</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(msia_left_join_pivot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 48 features and 30 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 109.5379 ymin: 0.855001 xmax: 119.2697 ymax: 7.380556
Geodetic CRS:  WGS 84
# A tibble: 48 × 31
   ADM1_EN ADM2_EN                               geometry crimes_causing_injur…¹
   &lt;chr&gt;   &lt;chr&gt;                       &lt;MULTIPOLYGON [°]&gt;                  &lt;dbl&gt;
 1 sabah   beaufort      (((115.58 5.213697, 115.5798 5.…                      1
 2 sabah   beluran       (((117.7142 6.260833, 117.7144 …                      5
 3 sabah   keningau      (((116.0938 4.861981, 116.0916 …                      7
 4 sabah   kinabatangan  (((119.2474 5.26962, 118.3465 5…                      7
 5 sabah   kota belud    (((116.61 6.666111, 116.6191 6.…                      9
 6 sabah   kota kinabalu (((116.3009 5.85547, 116.2936 5…                     41
 7 sabah   kota marudu   (((116.3408 6.401667, 116.3408 …                      4
 8 sabah   kudat         (((116.6292 6.688926, 116.6292 …                      4
 9 sabah   kunak         (((118.1334 4.862195, 118.1334 …                      0
10 sabah   lahad datu    (((117.746 4.758972, 117.7419 4…                      6
# ℹ 38 more rows
# ℹ abbreviated name: ¹​crimes_causing_injury_2020
# ℹ 27 more variables: crimes_causing_injury_2021 &lt;dbl&gt;,
#   crimes_causing_injury_2022 &lt;dbl&gt;, crimes_causing_injury_2023 &lt;dbl&gt;,
#   crimes_murder_2020 &lt;dbl&gt;, crimes_murder_2021 &lt;dbl&gt;,
#   crimes_murder_2022 &lt;dbl&gt;, crimes_murder_2023 &lt;dbl&gt;, crimes_rape_2020 &lt;dbl&gt;,
#   crimes_rape_2021 &lt;dbl&gt;, crimes_rape_2022 &lt;dbl&gt;, crimes_rape_2023 &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section>
<section id="projection-transformation" class="level3">
<h3 class="anchored" data-anchor-id="projection-transformation">3.6 Projection Transformation</h3>
<p>Acquiring the code from <a href="https://epsg.io/32649" class="uri">https://epsg.io/32649</a>,</p>
<ul>
<li>We will transform the it to East Malaysias’s projected coordinate system (UTM Zone 49N) with the EPSG code: 32649</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(msia_total_crimes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>msia <span class="ot">&lt;-</span> msia_left_join_pivot <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">32649</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>msia_total_crimes <span class="ot">&lt;-</span> msia_total_crimes <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">32649</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(msia_total_crimes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:32649 
  wkt:
PROJCRS["WGS 84 / UTM zone 49N",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 49N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",111,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Navigation and medium accuracy spatial referencing."],
        AREA["Between 108°E and 114°E, northern hemisphere between equator and 84°N, onshore and offshore. China. Hong Kong. Indonesia. Macao. Malaysia - East Malaysia - Sarawak. Mongolia. Russian Federation. Vietnam."],
        BBOX[0,108,84,114]],
    ID["EPSG",32649]]</code></pre>
</div>
</div>
</section>
<section id="visualisation" class="level3">
<h3 class="anchored" data-anchor-id="visualisation">3.7 Visualisation</h3>
</section>
<section id="writeread-rds" class="level3">
<h3 class="anchored" data-anchor-id="writeread-rds">3.8 Write/Read rds</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(msia_total_crimes, <span class="st">"data/rds/msia_total_crimes.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(msia, <span class="st">"data/rds/msia.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>msia <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/msia.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>msia_total_crimes <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/msia_total_crimes.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>east_msia <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/EAST_MSIA.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="shiny-visualisation-shiny-storyboard" class="level2">
<h2 class="anchored" data-anchor-id="shiny-visualisation-shiny-storyboard">4.0 Shiny Visualisation / Shiny Storyboard</h2>
<p>Below are screenshots from the shiny app depicting our Shiny Storyboard for East Malaysia</p>
<ul>
<li><p>EDA</p>
<ul>
<li><p>Basemap</p>
<ul>
<li>Basemap depicting all the different districts within East Malaysia</li>
</ul></li>
</ul>
<p><img src="images/clipboard-1910243840.png" class="img-fluid"></p>
<ul>
<li><p>Visualisation with different classification methods</p>
<ul>
<li><p>Able to filter based on total crimes, and other types such as rape, murder</p></li>
<li><p>Able to filter based on classification methods such as equal, quantile, pretty</p></li>
<li><p>Different Colour Schemes, Number of classes, and Transparency are also able to be adjusted</p></li>
</ul></li>
</ul></li>
</ul>
<p><img src="images/clipboard-2140389107.png" class="img-fluid"></p>
</section>
<section id="spatial-weights-and-applications" class="level2">
<h2 class="anchored" data-anchor-id="spatial-weights-and-applications">6.0 Spatial Weights and Applications</h2>
</section>
<section id="global-measures-of-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="global-measures-of-spatial-autocorrelation">6.0 Global Measures of Spatial Autocorrelation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(msia_total_crimes, </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">queen =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in poly2nb(msia_total_crimes, queen = TRUE): some observations have no neighbours;
if this seems unexpected, try increasing the snap argument.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in poly2nb(msia_total_crimes, queen = TRUE): neighbour object has 2 sub-graphs;
if this sub-graph count seems unexpected, try increasing the snap argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 48 
Number of nonzero links: 152 
Percentage nonzero weights: 6.597222 
Average number of links: 3.166667 
1 region with no links:
48
2 disjoint connected subgraphs
Link number distribution:

 0  1  2  3  4  5  6 
 1  1 12 17 11  4  2 
1 least connected region:
8 with 1 link
2 most connected regions:
43 45 with 6 links</code></pre>
</div>
</div>
<ul>
<li>If we attempt to use contiguity-based spatial weights to find neighbours, and use the queen method, we come up with a region that is not linked to any neighbours, which is incorrect.</li>
</ul>
<p>Lets print out the region with the 0 link. It turns out to be “w.p. labuan”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(msia_total_crimes<span class="sc">$</span>ADM1_EN[<span class="dv">48</span>], msia_total_crimes<span class="sc">$</span>ADM2_EN[<span class="dv">48</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "w.p. labuan" "w.p. labuan"</code></pre>
</div>
</div>
<p>Hence, instead of using contiguity-based methods to find neighbours, we need to swap to using distance-based methods instead to find neighbours and do our global spatial autocorrelation.</p>
<section id="configuring-and-binding-coordinates" class="level3">
<h3 class="anchored" data-anchor-id="configuring-and-binding-coordinates">6.1 Configuring and Binding coordinates</h3>
<section id="computing-longitude-and-latitude-to-achieve-coordinates" class="level4">
<h4 class="anchored" data-anchor-id="computing-longitude-and-latitude-to-achieve-coordinates">Computing longitude and latitude to achieve coordinates</h4>
<ul>
<li>longitude</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(msia_total_crimes<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>latitude</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(msia_total_crimes<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>bind the coordinates</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude latitude
[1,]   1022042 590736.6
[2,]   1202703 673828.1
[3,]   1080922 583121.1
[4,]   1298928 602534.3
[5,]   1110762 701440.2
[6,]   1071946 666813.2</code></pre>
</div>
</div>
</section>
</section>
<section id="computing-distance-based-neighbours" class="level3">
<h3 class="anchored" data-anchor-id="computing-distance-based-neighbours">6.2 Computing distance-based neighbours</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>k1 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in knn2nb(knearneigh(coords)): neighbour object has 8 sub-graphs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>k1dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">nbdists</span>(k1, coords, <span class="at">longlat =</span> <span class="cn">FALSE</span>))</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  18735   31304   40118   44676   50629  111017 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
This summary report shows that the largest first nearest neighbour distance is 111017 meters (UTM). As dnearneigh accepts meters and we need specify longlat = FALSE, lets round it up to 111100 meters and use this as our upper threshold will ensure us that all regions will at least have 1 neighbour.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
</section>
<section id="attempting-fixed-distance" class="level3">
<h3 class="anchored" data-anchor-id="attempting-fixed-distance">6.2.1 Attempting Fixed Distance</h3>
<ul>
<li>within 111100 meters radius</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>wm_d111100 <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span>, <span class="dv">111100</span>, <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>wm_d111100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 48 
Number of nonzero links: 318 
Percentage nonzero weights: 13.80208 
Average number of links: 6.625 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>n_comp <span class="ot">&lt;-</span> <span class="fu">n.comp.nb</span>(wm_d111100)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>n_comp<span class="sc">$</span>nc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(n_comp<span class="sc">$</span>comp.id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1 
48 </code></pre>
</div>
</div>
<section id="plotting-fixed-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="plotting-fixed-distance-weight-matrix">Plotting fixed distance weight matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the boundary and neighborhood structures with adjusted limits</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msia_total_crimes<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d111100, coords, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Plot 1st nearest neighbours (red lines)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># par(mfrow=c(1,2))</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msia_total_crimes<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"1st nearest neighbours"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(msia_total_crimes$geometry, border="lightgrey", main="Distance link")</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(wm_d111000, coords, add=TRUE, pch = 19, cex = 0.6)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="attempting-adaptive-distance" class="level3">
<h3 class="anchored" data-anchor-id="attempting-adaptive-distance">6.2.2 Attempting Adaptive Distance</h3>
<section id="computing-adaptive-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="computing-adaptive-distance-weight-matrix">Computing Adaptive Distance Weight matrix</h4>
<ul>
<li>Lets fix k=6, and no go too far ahead as greater the k, the further the search of neighbours would be.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>knn6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">6</span>))</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 48 
Number of nonzero links: 288 
Percentage nonzero weights: 12.5 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 48 
Number of nonzero links: 288 
Percentage nonzero weights: 12.5 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 48
 $ : int [1:6] 3 11 12 16 18 48
 $ : int [1:6] 5 7 8 13 14 19
 $ : int [1:6] 1 6 11 12 16 18
 $ : int [1:6] 2 9 10 14 15 17
 $ : int [1:6] 6 7 8 12 13 19
 $ : int [1:6] 3 5 11 12 13 19
 $ : int [1:6] 2 5 6 8 13 19
 $ : int [1:6] 2 5 6 7 13 19
 $ : int [1:6] 2 4 10 14 15 17
 $ : int [1:6] 2 4 9 14 15 17
 $ : int [1:6] 1 3 6 12 18 19
 $ : int [1:6] 3 5 6 11 13 19
 $ : int [1:6] 2 5 6 7 12 19
 $ : int [1:6] 2 4 9 10 13 17
 $ : int [1:6] 2 4 9 10 14 17
 $ : int [1:6] 1 3 18 30 31 48
 $ : int [1:6] 3 4 9 10 14 15
 $ : int [1:6] 1 3 11 16 30 48
 $ : int [1:6] 5 6 7 11 12 13
 $ : int [1:6] 29 33 39 40 42 44
 $ : int [1:6] 23 28 34 37 45 47
 $ : int [1:6] 26 36 40 41 44 46
 $ : int [1:6] 21 28 34 37 38 47
 $ : int [1:6] 25 27 35 36 38 43
 $ : int [1:6] 24 35 36 40 41 43
 $ : int [1:6] 27 32 36 41 43 45
 $ : int [1:6] 24 26 32 36 43 45
 $ : int [1:6] 21 23 27 38 45 47
 $ : int [1:6] 20 33 39 40 42 44
 $ : int [1:6] 1 3 16 18 31 48
 $ : int [1:6] 1 16 18 30 34 48
 $ : int [1:6] 22 26 27 36 45 46
 $ : int [1:6] 20 29 39 40 42 44
 $ : int [1:6] 16 21 23 30 31 37
 $ : int [1:6] 24 25 36 38 41 43
 $ : int [1:6] 25 26 35 40 41 43
 $ : int [1:6] 21 23 30 31 34 47
 $ : int [1:6] 24 27 35 36 43 47
 $ : int [1:6] 20 29 33 40 42 44
 $ : int [1:6] 22 25 26 36 41 46
 $ : int [1:6] 22 25 26 36 40 43
 $ : int [1:6] 20 22 29 33 39 44
 $ : int [1:6] 24 25 26 27 35 36
 $ : int [1:6] 22 29 39 40 42 46
 $ : int [1:6] 26 27 28 32 36 43
 $ : int [1:6] 22 26 32 40 41 44
 $ : int [1:6] 23 24 27 28 38 45
 $ : int [1:6] 1 11 16 18 30 31
 - attr(*, "region.id")= chr [1:48] "1" "2" "3" "4" ...
 - attr(*, "call")= language knearneigh(x = coords, k = 6)
 - attr(*, "sym")= logi FALSE
 - attr(*, "type")= chr "knn"
 - attr(*, "knn-k")= num 6
 - attr(*, "class")= chr "nb"
 - attr(*, "ncomp")=List of 2
  ..$ nc     : int 1
  ..$ comp.id: int [1:48] 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># table(msia$ADM2_EN, card(knn6))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-adaptive-distance-weight-matrix-in-shiny" class="level4">
<h4 class="anchored" data-anchor-id="plotting-adaptive-distance-weight-matrix-in-shiny">Plotting adaptive distance weight matrix in Shiny</h4>
<p><img src="images/clipboard-405232185.png" class="img-fluid"></p>
<p><u><strong>Decision:</strong></u></p>
<p>Both fixed distance and adaptive distance can be used. However, we need to take note that there are centroids located at the North-East side, on sea instead of on land due to multiple islands.</p>
</section>
</section>
<section id="global-moran-i-access-spatial-autocorrelation-using-adaptive-distance" class="level3">
<h3 class="anchored" data-anchor-id="global-moran-i-access-spatial-autocorrelation-using-adaptive-distance">6.2.3 Global Moran I: Access Spatial Autocorrelation using Adaptive Distance</h3>
<p>Next, <em>nb2listw()</em> is used to convert the nb object into spatial weights object.</p>
<p>We should also fix our style=“w”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>rsknn6 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn6, </span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">style=</span><span class="st">"W"</span>, </span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>rsknn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 48 
Number of nonzero links: 288 
Percentage nonzero weights: 12.5 
Average number of links: 6 
Non-symmetric neighbours list

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 48 2304 48 14.44444 196.6111</code></pre>
</div>
</div>
<section id="global-morans-i-test" class="level4">
<h4 class="anchored" data-anchor-id="global-morans-i-test">1. Global Moran’s I Test</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(msia_total_crimes<span class="sc">$</span>total_crimes, </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw=</span>rsknn6, </span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  msia_total_crimes$total_crimes  
weights: rsknn6    

Moran I statistic standard deviate = -0.0042367, p-value = 0.5017
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     -0.021512570      -0.021276596       0.003102251 </code></pre>
</div>
</div>
</section>
<section id="computing-monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="computing-monte-carlo-morans-i">2. .Computing Monte Carlo Moran’s I</h4>
<ul>
<li><p>set a seed of 1234</p></li>
<li><p>number of simulations = 1000</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>bperm_moran<span class="ot">=</span> <span class="fu">moran.mc</span>(msia_total_crimes<span class="sc">$</span>total_crimes, </span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">listw=</span>rsknn6, </span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">999</span>, </span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action=</span>na.omit)</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>bperm_moran</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  msia_total_crimes$total_crimes 
weights: rsknn6  
number of simulations + 1: 1000 

statistic = -0.021513, observed rank = 588, p-value = 0.412
alternative hypothesis: greater</code></pre>
</div>
</div>
<ul>
<li><p>moran I statistic: -0.021513 &lt; 0 show signs of regularity, however weak.</p></li>
<li><p>p-value = 0.412 &gt; 0.05, at the 95% confidence interval, we fail to reject the null hypothesis (which assumes spatial randomness), meaning to say that we do not have enough evidence to conclude that there is significant spatial autocorrelation and clustering.</p></li>
</ul>
<p>Hence, we accept null hypothesis (h0), and conclude that the result is not statistically significant, suggesting that the observed spatial pattern could be due to spatial randomness.</p>
</section>
<section id="visualising-monte-carlo-morans-i-using-shiny" class="level4">
<h4 class="anchored" data-anchor-id="visualising-monte-carlo-morans-i-using-shiny">3. Visualising Monte Carlo Moran’s I using Shiny</h4>
<p>Computing some basic statistics</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute mean</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bperm_moran<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.02278863</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute variance</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(bperm_moran<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003210544</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary bperm</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bperm_moran<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-0.132251 -0.062097 -0.033119 -0.022789  0.003581  0.298735 </code></pre>
</div>
</div>
<ul>
<li>plotting histogram using ggplot2 in Shiny</li>
</ul>
<p><img src="images/clipboard-396864859.png" class="img-fluid"></p>
</section>
</section>
<section id="spatial-correlogram" class="level3">
<h3 class="anchored" data-anchor-id="spatial-correlogram">6.3 Spatial Correlogram</h3>
<section id="compute-morans-i-spatial-correlogram" class="level4">
<h4 class="anchored" data-anchor-id="compute-morans-i-spatial-correlogram">Compute Moran’s I Spatial Correlogram</h4>
<p>In the code chunk below,&nbsp;<a href="https://r-spatial.github.io/spdep/reference/sp.correlogram.html"><code>sp.correlogram()</code></a>&nbsp;of&nbsp;<strong>spdep</strong>&nbsp;package is used to compute a <u><strong>6-lag</strong></u> spatial correlogram of GDPPC. The global spatial autocorrelation used in Moran’s I. The&nbsp;<strong>plot()</strong>&nbsp;of base Graph is then used to plot the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>MI_corr <span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(knn6,                            </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>                          msia_total_crimes<span class="sc">$</span>total_crimes,</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">order=</span><span class="dv">6</span>,  <span class="co">#lag-value: 6                           </span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method=</span><span class="st">"I"</span>,                            </span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">style=</span><span class="st">"W"</span>,</span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">zero.policy =</span> <span class="cn">TRUE</span>) </span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Looking at the first lag, it is close to 0, showing signs of randomness. This suggests that the total crimes of Thailand does not have spatial dependence. the following lags after shows negative Moran I, showing signs of regular patterns amongst 2nd order neighbours and below.</li>
</ul>
<p>By plotting the output might not allow us to provide complete interpretation. This is because not all autocorrelation values are statistically significant. Hence, it is important for us to examine the full analysis report by printing out the analysis results as in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatial correlogram for msia_total_crimes$total_crimes 
method: Moran's I
         estimate expectation   variance standard deviate Pr(I) two sided  
1 (48) -0.0215126  -0.0212766  0.0031023          -0.0042         0.99662  
2 (48) -0.0583456  -0.0212766  0.0023656          -0.7622         0.44597  
3 (48) -0.0289484  -0.0212766  0.0023930          -0.1568         0.87538  
4 (48) -0.1233814  -0.0212766  0.0032051          -1.8035         0.07130 .
5 (48) -0.0018402  -0.0212766  0.0048057           0.2804         0.77919  
6 (48)  0.1067613  -0.0212766  0.0041123           1.9966         0.04587 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="local-measures-of-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="local-measures-of-spatial-autocorrelation">7.0 Local Measures of Spatial Autocorrelation</h2>
<p>We need to use fixed-distance and adaptive-distance based methods for more reliable results.</p>
<ul>
<li>Local Moran’s I: Detect local clusters (high-high and low-low) and local outliers (high-low, low-high)</li>
</ul>
<section id="adaptive-distance-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="adaptive-distance-weight-matrix">7.1 Adaptive Distance Weight Matrix</h3>
<ul>
<li>stick to k=6, style=‘W’</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>knn6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">6</span>))</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 48 
Number of nonzero links: 288 
Percentage nonzero weights: 12.5 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<p>Next,&nbsp;<em>nb2listw()</em>&nbsp;is used to convert the nb object into spatial weights object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>knn6_lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn6, <span class="at">style =</span> <span class="st">'W'</span>)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(knn6_lw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 48 
Number of nonzero links: 288 
Percentage nonzero weights: 12.5 
Average number of links: 6 
Non-symmetric neighbours list
Link number distribution:

 6 
48 
48 least connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 with 6 links
48 most connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 with 6 links

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 48 2304 48 14.44444 196.6111</code></pre>
</div>
</div>
<p>Here, we can see that all 48 districts in East Malaysia have exactly 6 links.</p>
</section>
<section id="lisa" class="level3">
<h3 class="anchored" data-anchor-id="lisa">7.2 LISA</h3>
</section>
<section id="computing-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="computing-local-morans-i">7.2.1 Computing Local Moran’s I</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(msia_total_crimes<span class="sc">$</span>ADM2_EN)</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>localMI <span class="ot">&lt;-</span> <span class="fu">localmoran</span>(msia_total_crimes<span class="sc">$</span>total_crimes, knn6_lw)</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localMI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Ii          E.Ii       Var.Ii       Z.Ii Pr(z != E(Ii))
1  0.037083313 -2.760985e-03 1.963267e-02  0.2843652      0.7761305
2  0.022077090 -4.038567e-04 2.878511e-03  0.4190160      0.6752044
3  0.000755672 -3.059263e-07 2.181387e-06  0.5118501      0.6087559
4 -0.058333845 -1.283716e-03 9.141703e-03 -0.5966822      0.5507196
5 -0.046361434 -1.581031e-03 1.125562e-02 -0.4220884      0.6729605
6 -0.221639474 -9.445948e-02 6.099152e-01 -0.1628486      0.8706376</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">printCoefmat</span>(<span class="fu">data.frame</span>(</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  localMI[fips,], </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names=</span>msia_total_crimes<span class="sc">$</span>ADM2_EN[fips]),</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Ii        E.Ii      Var.Ii        Z.Ii Pr.z....E.Ii..
bau           -2.7246e-01 -2.5582e-03  1.8194e-02 -2.0010e+00         0.0454
beaufort       3.7083e-02 -2.7610e-03  1.9633e-02  2.8437e-01         0.7761
belaga        -1.5997e-02 -5.3574e-03  3.7996e-02 -5.4584e-02         0.9565
beluran        2.2077e-02 -4.0386e-04  2.8785e-03  4.1902e-01         0.6752
betong         1.4789e-01 -2.5582e-03  1.8194e-02  1.1154e+00         0.2647
bintulu       -3.8866e-02 -3.3160e-03  2.3566e-02 -2.3158e-01         0.8169
dalat          1.1819e-01 -6.4124e-03  4.5430e-02  5.8461e-01         0.5588
daro           1.2226e-01 -8.2617e-03  5.8423e-02  5.3998e-01         0.5892
julau          8.6043e-02 -5.6492e-03  4.0053e-02  4.5816e-01         0.6468
kanowit        1.0151e-01 -6.2559e-03  4.4328e-02  5.1186e-01         0.6088
kapit          1.6389e-01 -4.6619e-03  3.3086e-02  9.2662e-01         0.3541
keningau       7.5567e-04 -3.0593e-07  2.1814e-06  5.1185e-01         0.6088
kinabatangan  -5.8334e-02 -1.2837e-03  9.1417e-03 -5.9668e-01         0.5507
kota belud    -4.6361e-02 -1.5810e-03  1.1256e-02 -4.2209e-01         0.6730
kota kinabalu -2.2164e-01 -9.4459e-02  6.0992e-01 -1.6285e-01         0.8706
kota marudu   -3.0061e-02 -1.8243e-03  1.2984e-02 -2.4780e-01         0.8043
kuching       -1.1488e+00 -6.6699e-01  1.5838e+00 -3.8287e-01         0.7018
kudat         -3.7580e-02 -2.4597e-03  1.7495e-02 -2.6552e-01         0.7906
kunak         -1.1913e-01 -4.1402e-03  2.9399e-02 -6.7066e-01         0.5024
lahad datu     2.7014e-02 -5.3680e-04  3.8256e-03  4.4544e-01         0.6560
lawas          1.3462e-01 -4.1402e-03  2.9399e-02  8.0928e-01         0.4184
limbang        1.6251e-01 -4.7971e-03  3.4041e-02  9.0681e-01         0.3645
lubok antu     1.9112e-01 -4.1402e-03  2.9399e-02  1.1388e+00         0.2548
lundu         -3.1264e-01 -3.3018e-03  2.3466e-02 -2.0194e+00         0.0434
marudi        -9.5697e-04 -1.3551e-03  9.6497e-03  4.0534e-03         0.9968
matu           1.1176e-01 -8.2617e-03  5.8423e-02  4.9654e-01         0.6195
meradong       9.4401e-02 -3.7693e-03  2.6776e-02  5.9995e-01         0.5485
miri          -4.7316e-01 -5.2294e-02  3.5338e-01 -7.0798e-01         0.4790
mukah          9.0316e-02 -3.4158e-03  2.4273e-02  6.0162e-01         0.5474
papar          1.9145e-02 -1.7785e-04  1.2679e-03  5.4265e-01         0.5874
penampang      5.6857e-02 -1.7516e-03  1.2468e-02  5.2489e-01         0.5997
ranau         -8.0554e-02 -2.8653e-03  2.0372e-02 -5.4430e-01         0.5862
samarahan      3.2757e-01 -5.5206e-03  3.9147e-02  1.6835e+00         0.0923
sandakan      -1.7404e-02 -9.9733e-03  7.0405e-02 -2.8003e-02         0.9777
saratok        2.1459e-01 -5.3574e-03  3.7996e-02  1.1284e+00         0.2592
sarikei        7.2759e-02 -3.4158e-03  2.4273e-02  4.8893e-01         0.6249
semporna       4.1985e-02 -1.6702e-03  1.1890e-02  4.0036e-01         0.6889
serian        -2.7855e-02 -2.8587e-05  2.0383e-04 -1.9490e+00         0.0513
sibu          -7.1929e-01 -3.6978e-02  2.5392e-01 -1.3541e+00         0.1757
simunjan      -3.8169e-01 -4.5286e-03  3.2144e-02 -2.1037e+00         0.0354
sipitang       1.5227e-01 -5.7979e-03  4.1102e-02  7.7967e-01         0.4356
song           9.1833e-02 -5.6492e-03  4.0053e-02  4.8708e-01         0.6262
sri aman       1.1517e-01 -1.4285e-03  1.0171e-02  1.1562e+00         0.2476
tatau          1.8568e-01 -6.1013e-03  4.3240e-02  9.2231e-01         0.3564
tawau          6.4647e-02 -1.6482e-02  1.1559e-01  2.3863e-01         0.8114
tenom          8.8173e-02 -3.5317e-03  2.5094e-02  5.7891e-01         0.5626
tuaran        -9.6729e-02 -2.9715e-03  2.1125e-02 -6.4507e-01         0.5189
w.p. labuan    2.4793e-02 -1.0533e-04  7.5099e-04  9.0855e-01         0.3636</code></pre>
</div>
</div>
</section>
<section id="mapping-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="mapping-local-morans-i">7.2.2 Mapping local Moran’s I</h3>
<section id="append-to-local-morans-i-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="append-to-local-morans-i-dataframe">Append to local Moran’s I dataframe</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>msia_total_crimes.localMI <span class="ot">&lt;-</span> <span class="fu">cbind</span>(msia_total_crimes,localMI) <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Pr.Ii =</span> Pr.z....E.Ii..)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualising-local-morans-i-statistic-values-and-p-values" class="level4">
<h4 class="anchored" data-anchor-id="visualising-local-morans-i-statistic-values-and-p-values">Visualising local Moran’s I statistic values and p-values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>localMI_statistic.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(msia_total_crimes.localMI) <span class="sc">+</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>, </span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Moran's I statistic"</span>) <span class="sc">+</span></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title =</span> <span class="st">"local Moran's I statistic"</span>,</span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.position =</span> <span class="st">"center"</span>)</span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a>localMI_pvalues.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(msia_total_crimes.localMI) <span class="sc">+</span></span>
<span id="cb111-12"><a href="#cb111-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb111-13"><a href="#cb111-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb111-14"><a href="#cb111-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>, </span>
<span id="cb111-15"><a href="#cb111-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Moran's I p-values"</span>) <span class="sc">+</span></span>
<span id="cb111-16"><a href="#cb111-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb111-17"><a href="#cb111-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb111-18"><a href="#cb111-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title =</span> <span class="st">"local Moran's I p-values"</span>,</span>
<span id="cb111-19"><a href="#cb111-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb111-20"><a href="#cb111-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.position =</span> <span class="st">"center"</span>)</span>
<span id="cb111-21"><a href="#cb111-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-22"><a href="#cb111-22" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(localMI_statistic.map, localMI_pvalues.map, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "Ii" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>write to rds so that can be read in the ShinyApp file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(localMI_statistic.map, <span class="st">"data/rds/localMI_statistic.map.rds"</span>)</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(localMI_pvalues.map, <span class="st">"data/rds/localMI_pvalues.map.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="creating-lisa-cluster-map" class="level3">
<h3 class="anchored" data-anchor-id="creating-lisa-cluster-map">7.3 Creating LISA Cluster Map</h3>
<ul>
<li>In the Shiny App, under Local Measures tab, the following screenshot depicts selection between Moran Scatterplot and Moran Scatterplot with Standardized variable</li>
</ul>
<p><img src="images/clipboard-2091516722.png" class="img-fluid"></p>
</section>
<section id="plotting-moran-scatterplot" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot">7.3.1 Plotting Moran scatterplot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>nci <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(msia_total_crimes<span class="sc">$</span>total_crimes, knn6_lw,                   </span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels=</span><span class="fu">as.character</span>(msia_total_crimes<span class="sc">$</span>ADM2_EN),</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xlab=</span><span class="st">"Total Cases over all years"</span>,                    </span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="st">"Spatially Lag Total Cases over all years"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="plotting-moran-scatterplot-with-standardized-variable" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot-with-standardized-variable">7.3.2 Plotting Moran scatterplot with standardized variable</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>msia_total_crimes<span class="sc">$</span>Z.total_crimes<span class="ot">&lt;-</span> <span class="fu">scale</span>(msia_total_crimes<span class="sc">$</span>total_crimes) <span class="sc">%&gt;%</span> </span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  as.vector </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>nci2 <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(msia_total_crimes<span class="sc">$</span>total_crimes, knn6_lw,                   </span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels=</span><span class="fu">as.character</span>(msia_total_crimes<span class="sc">$</span>ADM2_EN),</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xlab=</span><span class="st">"z- Total Cases over all years"</span>,                    </span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="st">"Spatially Lag z- Total Cases over all years"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lisa-map-classes" class="level3">
<h3 class="anchored" data-anchor-id="lisa-map-classes">7.3.3 LISA map classes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>quadrant <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode=</span><span class="st">"numeric"</span>,<span class="at">length=</span><span class="fu">nrow</span>(localMI))</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>msia_total_crimes<span class="sc">$</span>lag_total_crimes <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(knn6_lw, msia_total_crimes<span class="sc">$</span>total_crimes)</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a>DV <span class="ot">&lt;-</span> msia_total_crimes<span class="sc">$</span>lag_total_crimes <span class="sc">-</span> <span class="fu">mean</span>(msia_total_crimes<span class="sc">$</span>lag_total_crimes)    </span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a>LM_I <span class="ot">&lt;-</span> localMI[,<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">mean</span>(localMI[,<span class="dv">1</span>])    </span>
<span id="cb117-6"><a href="#cb117-6" aria-hidden="true" tabindex="-1"></a>signif <span class="ot">&lt;-</span> <span class="fl">0.05</span>       </span>
<span id="cb117-7"><a href="#cb117-7" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb117-8"><a href="#cb117-8" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb117-9"><a href="#cb117-9" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">3</span>  </span>
<span id="cb117-10"><a href="#cb117-10" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">4</span>     </span>
<span id="cb117-11"><a href="#cb117-11" aria-hidden="true" tabindex="-1"></a>quadrant[localMI[,<span class="dv">5</span>]<span class="sc">&gt;</span>signif] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-lisa-map" class="level3">
<h3 class="anchored" data-anchor-id="plotting-lisa-map">7.3.4 <strong>Plotting LISA map</strong></h3>
<ul>
<li>In Shiny: LISA Map</li>
</ul>
<p><img src="images/clipboard-573219080.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|fig-width: 12</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="co">#|fig-height: 10</span></span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>total_crimes <span class="ot">&lt;-</span> <span class="fu">qtm</span>(msia_total_crimes, <span class="st">"total_crimes"</span>)</span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>msia_total_crimes.localMI<span class="sc">$</span>quadrant <span class="ot">&lt;-</span> quadrant</span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>)</span>
<span id="cb118-9"><a href="#cb118-9" aria-hidden="true" tabindex="-1"></a>clusters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"insignificant"</span>, <span class="st">"low-low"</span>, <span class="st">"low-high"</span>, <span class="st">"high-low"</span>, <span class="st">"high-high"</span>)</span>
<span id="cb118-10"><a href="#cb118-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-11"><a href="#cb118-11" aria-hidden="true" tabindex="-1"></a>LISAmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(msia_total_crimes.localMI) <span class="sc">+</span></span>
<span id="cb118-12"><a href="#cb118-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"quadrant"</span>, </span>
<span id="cb118-13"><a href="#cb118-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"cat"</span>, </span>
<span id="cb118-14"><a href="#cb118-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> colors[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>], </span>
<span id="cb118-15"><a href="#cb118-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],</span>
<span id="cb118-16"><a href="#cb118-16" aria-hidden="true" tabindex="-1"></a>          <span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb118-17"><a href="#cb118-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb118-18"><a href="#cb118-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span>
<span id="cb118-19"><a href="#cb118-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-20"><a href="#cb118-20" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(total_crimes, LISAmap, </span>
<span id="cb118-21"><a href="#cb118-21" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>outliers_hotspots <span class="ot">&lt;-</span> msia_total_crimes.localMI <span class="sc">%&gt;%</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(quadrant <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cluster =</span> <span class="fu">case_when</span>(</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>    quadrant <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Low-Low (Hotspot)"</span>,</span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>    quadrant <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Low-High (Outlier)"</span>,</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>    quadrant <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"High-Low (Outlier)"</span>,</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>    quadrant <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"High-High (Hotspot)"</span>,</span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Insignificant"</span>  <span class="co"># Just a fallback, should not occur</span></span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(outliers_hotspots[, <span class="fu">c</span>(<span class="st">"ADM1_EN"</span>, <span class="st">"quadrant"</span>, <span class="st">"cluster"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 337381.7 ymin: 108268.9 xmax: 514052.4 ymax: 227502.6
Projected CRS: WGS 84 / UTM zone 49N
   ADM1_EN quadrant            cluster                       geometry
20 sarawak        2 Low-High (Outlier) MULTIPOLYGON (((406897.6 13...
33 sarawak        2 Low-High (Outlier) MULTIPOLYGON (((387584.1 18...
44 sarawak        2 Low-High (Outlier) MULTIPOLYGON (((474075.3 17...</code></pre>
</div>
</div>
</section>
<section id="computing-gi-statistics-total-cases-over-the-years" class="level3">
<h3 class="anchored" data-anchor-id="computing-gi-statistics-total-cases-over-the-years">7.4 Computing Gi Statistics (total cases over the years)</h3>
<p>Next, we need to perform Gi Statistics, for each fixed distance and adaptive distances. The computed Gi statistic will give us a representation of a Z-score. Greater <u><strong>local Gi</strong></u> represent a greater intensity of <strong>clustering</strong> and the direction (positive or negative) indicates <strong>high or low clusters.</strong></p>
</section>
<section id="gi-statistics-for-adaptive-distance" class="level3">
<h3 class="anchored" data-anchor-id="gi-statistics-for-adaptive-distance">7.4.1 Gi statistics for adaptive distance</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(msia_total_crimes<span class="sc">$</span>ADM2_EN) </span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>gi.adaptive <span class="ot">&lt;-</span> <span class="fu">localG</span>(msia_total_crimes<span class="sc">$</span>total_crimes, knn6_lw) </span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>msia_total_crimes.gi <span class="ot">&lt;-</span> <span class="fu">cbind</span>(msia_total_crimes, <span class="fu">as.matrix</span>(gi.adaptive)) <span class="sc">%&gt;%</span>   </span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_adaptive =</span> as.matrix.gi.adaptive.)  </span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-6"><a href="#cb121-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the threshold for hotspot areas (e.g., top 5% of Gi scores) </span></span>
<span id="cb121-7"><a href="#cb121-7" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fu">quantile</span>(msia_total_crimes.gi<span class="sc">$</span>gstat_adaptive, <span class="fl">0.95</span>)    </span>
<span id="cb121-8"><a href="#cb121-8" aria-hidden="true" tabindex="-1"></a>hotspots <span class="ot">&lt;-</span> msia_total_crimes.gi <span class="sc">%&gt;%</span>   </span>
<span id="cb121-9"><a href="#cb121-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gstat_adaptive <span class="sc">&gt;=</span> threshold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>hotspots_province_gstatscore <span class="ot">&lt;-</span> hotspots <span class="sc">%&gt;%</span>   </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM2_EN, gstat_adaptive) <span class="sc">%&gt;%</span>   </span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(gstat_adaptive))   </span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(hotspots_province_gstatscore)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 337381.7 ymin: 108268.9 xmax: 514052.4 ymax: 227502.6
Projected CRS: WGS 84 / UTM zone 49N
   ADM2_EN gstat_adaptive                       geometry
1 simunjan       2.103660 MULTIPOLYGON (((474075.3 17...
2    lundu       2.019375 MULTIPOLYGON (((387584.1 18...
3      bau       2.000985 MULTIPOLYGON (((406897.6 13...</code></pre>
</div>
</div>
</section>
<section id="plotting-and-mapping-gi-values-with-adaptive-distance-weights" class="level3">
<h3 class="anchored" data-anchor-id="plotting-and-mapping-gi-values-with-adaptive-distance-weights">7.4.2 Plotting and Mapping Gi values with adaptive distance weights</h3>
<ul>
<li>In Shiny: Gi Map</li>
</ul>
<p><img src="images/clipboard-1323571806.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>Gimap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(msia_total_crimes.gi) <span class="sc">+</span>    </span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"gstat_adaptive"</span>,            </span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,            </span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-RdBu"</span>,            </span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Gi"</span>) <span class="sc">+</span>    </span>
<span id="cb124-6"><a href="#cb124-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>   </span>
<span id="cb124-7"><a href="#cb124-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(hotspots) <span class="sc">+</span>    </span>
<span id="cb124-8"><a href="#cb124-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"ADM2_EN"</span>, <span class="at">size =</span> <span class="fl">0.7</span>, <span class="at">col=</span><span class="st">"blue"</span>) <span class="sc">+</span>    </span>
<span id="cb124-9"><a href="#cb124-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(     </span>
<span id="cb124-10"><a href="#cb124-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title =</span> <span class="st">"Gi map showing hotspots"</span>,     </span>
<span id="cb124-11"><a href="#cb124-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.size =</span> <span class="dv">1</span>,     </span>
<span id="cb124-12"><a href="#cb124-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.position =</span> <span class="st">"center"</span>,     </span>
<span id="cb124-13"><a href="#cb124-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.show =</span> <span class="cn">TRUE</span>,     </span>
<span id="cb124-14"><a href="#cb124-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text.size =</span> <span class="dv">1</span>,   <span class="co"># Reduce the text size     </span></span>
<span id="cb124-15"><a href="#cb124-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">frame =</span> <span class="cn">FALSE</span>)     </span>
<span id="cb124-16"><a href="#cb124-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-17"><a href="#cb124-17" aria-hidden="true" tabindex="-1"></a>Gimap </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "gstat_adaptive" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex03_files/figure-html/unnamed-chunk-69-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Similarly, what inference can we draw from the adaptive-based plot?</p>
<ul>
<li>Two <strong>hotspots</strong> (red) are identified in East Malaysia, with both hotspots located around the central region. These hotspots comprise the provinces of <strong>Simunjan, Lundu,</strong> and <strong>Bau</strong>, with gstat_adaptive scores ranging from approximately 2.00 to 2.10. This suggests these provinces have higher case concentrations compared to their neighbors, indicating positive spatial clustering.</li>
</ul></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>