---
title: "Take-home Exercise 1: Geospatial Analytics for Social Good - Application of Spatial and Spatio-temporal Point Patterns Analysis to discover the geographical distribution of Armed Conflict in Myanmar"
author: "Marcus Jaeson Yeo"
date: "September 08, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
---

## 1.0 Introduction

## 2.0 Importing Packages

-   sf

-   raster

-   spatstat

-   sparr

-   tmap

-   tidyverse

```{r}
pacman::p_load(sf, raster, spatstat, sparr, tmap, tidyverse)
```

## 3.0 Importing Datasets into Environment

-   geospatial

-   aspatial (csv)

    ```{r}
    myanmar_sf <- read_csv("data/aspatial/2021-01-01-2024-06-30-Myanmar.csv")
    myanmar_sf
    ```

    ```{r}
    myanmar_sf <- read_csv("data/aspatial/2021-01-01-2024-06-30-Myanmar.csv") %>%
      st_as_sf(coords = c("longitude", "latitude"),
               crs = 4326) %>%
      st_transform(crs=32748)
    ```

## 4.0 Projection Transformation

## 5.0 Data Wrangling

## 6.0 Exploratory Spatial Data Analysis

## 7.0 Measuring Dispersion??

## 8.0 First Order/Second Order SPPA

## 9.0 Kernel Density Estimation

## 10.0 Conclusion

## References
