<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcus Jaeson Yeo">
<meta name="dcterms.date" content="2024-09-26">

<title>IS415-GAA - Take-home Exercise 2: Application of Geospatial Analysis Methods to Discover Thailand Drug Abuse at the Province Level</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex01/hands-on-ex1.html">
 <span class="dropdown-text">Hands-on Exercise 1: Geospatial Data Science with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex02/hands-on-ex2.html">
 <span class="dropdown-text">Hands-on Exercise 2: Thematic Mapping and GeoVisualisation with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p1/hands-on-ex3_p1.html">
 <span class="dropdown-text">Hands-on Exercise 3: 1st Order SPAA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex03/hands-on-ex3_p2/hands-on-ex3_p2.html">
 <span class="dropdown-text">Hands-on Exercise 3: 2nd Order SPAA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex04/in-class_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4: ICE4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex05/hands-on-ex5.html">
 <span class="dropdown-text">Hands-on Exercise 5: Spatial Weights and Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex06/hands-on-ex6_global/hands-on-ex6_global.html">
 <span class="dropdown-text">Hands-on Exercise 6: Global Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on-exercises/Hands-on_Ex06/hands-on-ex6_local/hands-on-ex6_local.html">
 <span class="dropdown-text">Hands-on Exercise 6: Local Measures of Spatial Autocorrelation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex01/in-class_Ex01-v2.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex02/in-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex03/in-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex04/in-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex05/in-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_exercises/in-class_ex06/in-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../take-home_exercises/take-home_ex01/take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../take-home_exercises/take-home_ex02/take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1.0 Introduction</a></li>
  <li><a href="#importing-packages" id="toc-importing-packages" class="nav-link" data-scroll-target="#importing-packages">2.0 Importing Packages</a></li>
  <li><a href="#importing-datasets-into-environment" id="toc-importing-datasets-into-environment" class="nav-link" data-scroll-target="#importing-datasets-into-environment">3.0 Importing Datasets into Environment</a></li>
  <li><a href="#data-wrangling-necessary-projection-transformation" id="toc-data-wrangling-necessary-projection-transformation" class="nav-link" data-scroll-target="#data-wrangling-necessary-projection-transformation">4.0 Data Wrangling + necessary Projection Transformation</a>
  <ul class="collapse">
  <li><a href="#dropping-redundant-columns-left-join" id="toc-dropping-redundant-columns-left-join" class="nav-link" data-scroll-target="#dropping-redundant-columns-left-join">4.1 Dropping redundant columns + Left Join</a></li>
  <li><a href="#dropping-and-summing-total-number-of-drug-cases" id="toc-dropping-and-summing-total-number-of-drug-cases" class="nav-link" data-scroll-target="#dropping-and-summing-total-number-of-drug-cases">4.2 Dropping and summing total number of drug cases</a></li>
  <li><a href="#projection-transformation" id="toc-projection-transformation" class="nav-link" data-scroll-target="#projection-transformation">4.3 Projection Transformation</a></li>
  </ul></li>
  <li><a href="#exploratory-spatial-data-analysis" id="toc-exploratory-spatial-data-analysis" class="nav-link" data-scroll-target="#exploratory-spatial-data-analysis">5.0 Exploratory Spatial Data Analysis</a>
  <ul class="collapse">
  <li><a href="#plotting" id="toc-plotting" class="nav-link" data-scroll-target="#plotting">5.1 Plotting</a></li>
  <li><a href="#total-number-of-cases-by-each-year-and-each-province" id="toc-total-number-of-cases-by-each-year-and-each-province" class="nav-link" data-scroll-target="#total-number-of-cases-by-each-year-and-each-province">5.1.1 Total number of cases by each year and each province</a></li>
  <li><a href="#side-by-side-view-of-province-and-total-no-of-drug-cases-in-year-2017" id="toc-side-by-side-view-of-province-and-total-no-of-drug-cases-in-year-2017" class="nav-link" data-scroll-target="#side-by-side-view-of-province-and-total-no-of-drug-cases-in-year-2017">5.1.2 Side by side view of province and total no of drug cases in year 2017</a></li>
  <li><a href="#top-5-provinces-with-the-highest-number-of-drug-cases-over-all-the-years" id="toc-top-5-provinces-with-the-highest-number-of-drug-cases-over-all-the-years" class="nav-link" data-scroll-target="#top-5-provinces-with-the-highest-number-of-drug-cases-over-all-the-years">5.1.3 Top 5 Provinces with the highest number of drug cases over all the years</a></li>
  <li><a href="#visualising-equal-and-quantile-over-all-the-years" id="toc-visualising-equal-and-quantile-over-all-the-years" class="nav-link" data-scroll-target="#visualising-equal-and-quantile-over-all-the-years">5.2 Visualising Equal and Quantile over all the years</a></li>
  </ul></li>
  <li><a href="#global-measures-of-spatial-autocorrelation" id="toc-global-measures-of-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-measures-of-spatial-autocorrelation">6.0 Global Measures of Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#configuring-and-binding-coordinates" id="toc-configuring-and-binding-coordinates" class="nav-link" data-scroll-target="#configuring-and-binding-coordinates">6.1 Configuring and Binding coordinates</a></li>
  <li><a href="#computing-distance-based-neighbours" id="toc-computing-distance-based-neighbours" class="nav-link" data-scroll-target="#computing-distance-based-neighbours">6.2 Computing distance-based neighbours</a></li>
  <li><a href="#fixed-distance" id="toc-fixed-distance" class="nav-link" data-scroll-target="#fixed-distance">6.2.1 Fixed Distance</a></li>
  <li><a href="#adaptive-distance" id="toc-adaptive-distance" class="nav-link" data-scroll-target="#adaptive-distance">6.2.2 Adaptive Distance</a></li>
  <li><a href="#global-moran-i-access-spatial-autocorrelation-using-adaptive-distance" id="toc-global-moran-i-access-spatial-autocorrelation-using-adaptive-distance" class="nav-link" data-scroll-target="#global-moran-i-access-spatial-autocorrelation-using-adaptive-distance">6.2.3 Global Moran I: Access Spatial Autocorrelation using Adaptive Distance</a></li>
  <li><a href="#spatial-correlogram" id="toc-spatial-correlogram" class="nav-link" data-scroll-target="#spatial-correlogram">6.3 Spatial Correlogram</a></li>
  </ul></li>
  <li><a href="#local-measures-of-spatial-autocorrelation" id="toc-local-measures-of-spatial-autocorrelation" class="nav-link" data-scroll-target="#local-measures-of-spatial-autocorrelation">7.0 Local Measures of Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#fixed-distance-weight-matrix" id="toc-fixed-distance-weight-matrix" class="nav-link" data-scroll-target="#fixed-distance-weight-matrix">7.1 Fixed Distance Weight Matrix</a></li>
  <li><a href="#adaptive-distance-weight-matrix" id="toc-adaptive-distance-weight-matrix" class="nav-link" data-scroll-target="#adaptive-distance-weight-matrix">7.2 Adaptive Distance Weight Matrix</a></li>
  <li><a href="#computing-gi-statistics" id="toc-computing-gi-statistics" class="nav-link" data-scroll-target="#computing-gi-statistics">7.3 Computing Gi Statistics</a></li>
  <li><a href="#gi-statistics-for-fixed-distance" id="toc-gi-statistics-for-fixed-distance" class="nav-link" data-scroll-target="#gi-statistics-for-fixed-distance">7.3.1 Gi statistics for fixed distance</a></li>
  <li><a href="#gi-statistics-for-adaptive-distance" id="toc-gi-statistics-for-adaptive-distance" class="nav-link" data-scroll-target="#gi-statistics-for-adaptive-distance">7.3.2 Gi statistics for adaptive distance</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">9.0 Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2: Application of Geospatial Analysis Methods to Discover Thailand Drug Abuse at the Province Level</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marcus Jaeson Yeo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 26, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 12, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1.0 Introduction</h2>
<section id="context" class="level4">
<h4 class="anchored" data-anchor-id="context">Context:</h4>
<p>Drug abuse is associated with significant negative health, financial and social consequences. Yet, illicit drug consumption remains highly prevalent and continues to be a growing problem worldwide. In 2021, 1 in 17 people, aged 15–64 in the world had used a drug in the past 12 months. Notwithstanding population growth, the estimated number of drug users grew from 240 million in 2011 to 296 million in 2021.</p>
<p>The geopolitics of Thailand which is near the <a href="https://en.wikipedia.org/wiki/Golden_Triangle_(Southeast_Asia)">Golden Triangle</a> of Indochina, the largest drug production site in Asia, and the constant transportation infrastructure development made Thailand became market and transit routes for drug trafficking to the third countries.</p>
<p>In Thailand, drug abuse is one of the major social issue. There are about 2.7 million youths using drugs in Thailand. Among youths aged between 15 and 19 years, there are about 300,000 who have needs for drug treatment. Most of Thai youths involved with drugs are vocational-school students, which nearly doubles in number compared to secondary-school students.</p>
<p>Figure below shows geographic distribution of drug use cases by province and by year.</p>
</section>
<section id="objectives" class="level4">
<h4 class="anchored" data-anchor-id="objectives">Objectives:</h4>
<ul>
<li><p>if the key indicators of drug abuse of Thailand are independent from space. (spatial independent, randomly distributed) (spatial weights and applications)</p></li>
<li><p>If the indicators of drug abuse is indeed spatial dependent, then, you would like to detect where are the clusters and outliers, and the hotspots. (no need for emerging hotspots)</p></li>
<li><p>Last but not least, you are also interested to investigate how the observation above evolve over time. (no need for spatial-temporal)</p></li>
</ul>
<hr>
</section>
</section>
<section id="importing-packages" class="level2">
<h2 class="anchored" data-anchor-id="importing-packages">2.0 Importing Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, lubridate, tmap, tidyverse, spdep, sfdep, smoothr, dplyr, tidyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="importing-datasets-into-environment" class="level2">
<h2 class="anchored" data-anchor-id="importing-datasets-into-environment">3.0 Importing Datasets into Environment</h2>
<ul>
<li><p>geospatial (admin1 (province level))</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>thailand_boundary <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn=</span><span class="st">"data/geospatial/"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">layer=</span><span class="st">"tha_admbnda_adm1_rtsd_20220121"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `tha_admbnda_adm1_rtsd_20220121' from data source 
  `C:\marcus159260\IS415-GAA\take-home_exercises\take-home_ex02\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 77 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(thailand_boundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77 17</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(thailand_boundary, max.plot=16)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>aspatial</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>thailand_sf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/thai_drug_offenses_2017_2022.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 7392 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): types_of_drug_offenses, province_th, province_en
dbl (2): fiscal_year, no_cases

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(thailand_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7392    5</code></pre>
</div>
</div></li>
</ul>
<hr>
</section>
<section id="data-wrangling-necessary-projection-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling-necessary-projection-transformation">4.0 Data Wrangling + necessary Projection Transformation</h2>
<section id="dropping-redundant-columns-left-join" class="level3">
<h3 class="anchored" data-anchor-id="dropping-redundant-columns-left-join">4.1 Dropping redundant columns + Left Join</h3>
<ul>
<li>Dropping columns with NA and columns that do not give us valuable information</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>thailand_boundary <span class="ot">&lt;-</span> thailand_boundary <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">14</span><span class="sc">:</span><span class="dv">17</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>thailand_sf <span class="ot">&lt;-</span> thailand_sf <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>We need to further understand a bit more about the common identifier (province), hence printing the unique provinces, which is both <u>76</u> unique provinces for both boundary and sf.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>unique_provinces_boundary <span class="ot">&lt;-</span> <span class="fu">unique</span>(thailand_boundary<span class="sc">$</span>ADM1_EN)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>unique_provinces_boundary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Bangkok"                  "Samut Prakan"            
 [3] "Nonthaburi"               "Pathum Thani"            
 [5] "Phra Nakhon Si Ayutthaya" "Ang Thong"               
 [7] "Lop Buri"                 "Sing Buri"               
 [9] "Chai Nat"                 "Saraburi"                
[11] "Chon Buri"                "Rayong"                  
[13] "Chanthaburi"              "Trat"                    
[15] "Chachoengsao"             "Prachin Buri"            
[17] "Nakhon Nayok"             "Sa Kaeo"                 
[19] "Nakhon Ratchasima"        "Buri Ram"                
[21] "Surin"                    "Si Sa Ket"               
[23] "Ubon Ratchathani"         "Yasothon"                
[25] "Chaiyaphum"               "Amnat Charoen"           
[27] "Bueng Kan"                "Nong Bua Lam Phu"        
[29] "Khon Kaen"                "Udon Thani"              
[31] "Loei"                     "Nong Khai"               
[33] "Maha Sarakham"            "Roi Et"                  
[35] "Kalasin"                  "Sakon Nakhon"            
[37] "Nakhon Phanom"            "Mukdahan"                
[39] "Chiang Mai"               "Lamphun"                 
[41] "Lampang"                  "Uttaradit"               
[43] "Phrae"                    "Nan"                     
[45] "Phayao"                   "Chiang Rai"              
[47] "Mae Hong Son"             "Nakhon Sawan"            
[49] "Uthai Thani"              "Kamphaeng Phet"          
[51] "Tak"                      "Sukhothai"               
[53] "Phitsanulok"              "Phichit"                 
[55] "Phetchabun"               "Ratchaburi"              
[57] "Kanchanaburi"             "Suphan Buri"             
[59] "Nakhon Pathom"            "Samut Sakhon"            
[61] "Samut Songkhram"          "Phetchaburi"             
[63] "Prachuap Khiri Khan"      "Nakhon Si Thammarat"     
[65] "Krabi"                    "Phangnga"                
[67] "Phuket"                   "Surat Thani"             
[69] "Ranong"                   "Chumphon"                
[71] "Songkhla"                 "Satun"                   
[73] "Trang"                    "Phatthalung"             
[75] "Pattani"                  "Yala"                    
[77] "Narathiwat"              </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>unique_provinces_sf <span class="ot">&lt;-</span> <span class="fu">unique</span>(thailand_sf<span class="sc">$</span>province_en)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>unique_provinces_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Bangkok"                  "Chai Nat"                
 [3] "Nonthaburi"               "Pathum Thani"            
 [5] "Phra Nakhon Si Ayutthaya" "Loburi"                  
 [7] "Samut Prakan"             "Saraburi"                
 [9] "Sing Buri"                "Ang Thong"               
[11] "Chanthaburi"              "Chachoengsao"            
[13] "Chon Buri"                "Trat"                    
[15] "Nakhon Nayok"             "Prachin Buri"            
[17] "Rayong"                   "Sa Kaeo"                 
[19] "Chaiyaphum"               "Nakhon Ratchasima"       
[21] "Buri Ram"                 "Yasothon"                
[23] "Si Sa Ket"                "Surin"                   
[25] "Amnat Charoen"            "Ubon Ratchathani"        
[27] "Kalasin"                  "Khon Kaen"               
[29] "Nakhon Phanom"            "buogkan"                 
[31] "Maha Sarakham"            "Mukdahan"                
[33] "Roi Et"                   "Loei"                    
[35] "Sakon Nakhon"             "Nong Khai"               
[37] "Nong Bua Lam Phu"         "Udon Thani"              
[39] "Chiang Rai"               "Chiang Mai"              
[41] "Nan"                      "Phayao"                  
[43] "Phrae"                    "Mae Hong Son"            
[45] "Lampang"                  "Lamphun"                 
[47] "Kamphaeng Phet"           "Tak"                     
[49] "Nakhon Sawan"             "Phichit"                 
[51] "Phitsanulok"              "Phetchabun"              
[53] "Sukhothai"                "Uttaradit"               
[55] "Uthai Thani"              "Kanchanaburi"            
[57] "Nakhon Pathom"            "Prachuap Khiri Khan"     
[59] "Phetchaburi"              "Ratchaburi"              
[61] "Samut Songkhram"          "Samut Sakhon"            
[63] "Suphan Buri"              "Krabi"                   
[65] "Chumphon"                 "Nakhon Si Thammarat"     
[67] "Phangnga"                 "Phuket"                  
[69] "Ranong"                   "Surat Thani"             
[71] "Trang"                    "Narathiwat"              
[73] "Pattani"                  "Phatthalung"             
[75] "Yala"                     "Songkhla"                
[77] "Satun"                   </code></pre>
</div>
</div>
<ul>
<li><p>After studying the columns of both the geospatial and aspatial data, we see that the aspatial data (thailand_sf) lacks geometrical data (such as the latitude and longitude spatial features). We need to join both boundary and working data with its common columns: <strong>ADM1_EN</strong> (thailand_boundary) and <strong>province_en</strong> (thailand_sf).</p>
<ul>
<li>First, we need to mutate to get the common identifier</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>thailand_boundary <span class="ot">&lt;-</span> thailand_boundary <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ADM1_EN =</span> <span class="fu">str_to_lower</span>(ADM1_EN),  <span class="co"># Convert to lowercase</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ADM1_EN =</span> <span class="fu">str_trim</span>(ADM1_EN))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>thailand_sf <span class="ot">&lt;-</span> thailand_sf <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">province_en =</span> <span class="fu">str_to_lower</span>(province_en),  <span class="co"># Convert to lowercase</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">province_en =</span> <span class="fu">str_trim</span>(province_en))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Second, we perform a left join. After left join, impute the 2 province rows with missing values with the mean values.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>thailand_left_join <span class="ot">&lt;-</span> thailand_boundary <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(thailand_sf, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ADM1_EN"</span> <span class="ot">=</span> <span class="st">"province_en"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">7</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>missing_provinces <span class="ot">&lt;-</span> thailand_left_join <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(no_cases)) <span class="sc">%&gt;%</span>  <span class="co"># Check for NA in the case column</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM1_EN)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_provinces)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 2 features and 1 field
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 100.42 ymin: 14.64684 xmax: 104.19 ymax: 18.44898
Geodetic CRS:  WGS 84
    ADM1_EN                       geometry
1  Lop Buri MULTIPOLYGON (((101.3453 15...
2 Bueng Kan MULTIPOLYGON (((103.405 18....</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>thailand_left_join_filtered <span class="ot">&lt;-</span> thailand_left_join <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(no_cases))  <span class="co"># Exclude rows where no_cases is NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dropping-and-summing-total-number-of-drug-cases" class="level3">
<h3 class="anchored" data-anchor-id="dropping-and-summing-total-number-of-drug-cases">4.2 Dropping and summing total number of drug cases</h3>
<section id="understanding-our-data" class="level4">
<h4 class="anchored" data-anchor-id="understanding-our-data">Understanding our data</h4>
<ul>
<li>unique years, provinces, and types of drug offenses</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>unique_years <span class="ot">=</span> <span class="fu">unique</span>(thailand_left_join_filtered<span class="sc">$</span>fiscal_year)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>unique_provinces <span class="ot">=</span> <span class="fu">unique</span>(thailand_left_join_filtered<span class="sc">$</span>ADM1_EN)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>unique_types <span class="ot">=</span> <span class="fu">unique</span>(thailand_left_join_filtered<span class="sc">$</span>types_of_drug_offenses)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>unique_years</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2017 2018 2019 2020 2021 2022</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>unique_provinces</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Bangkok"                  "Samut Prakan"            
 [3] "Nonthaburi"               "Pathum Thani"            
 [5] "Phra Nakhon Si Ayutthaya" "Ang Thong"               
 [7] "Sing Buri"                "Chai Nat"                
 [9] "Saraburi"                 "Chon Buri"               
[11] "Rayong"                   "Chanthaburi"             
[13] "Trat"                     "Chachoengsao"            
[15] "Prachin Buri"             "Nakhon Nayok"            
[17] "Sa Kaeo"                  "Nakhon Ratchasima"       
[19] "Buri Ram"                 "Surin"                   
[21] "Si Sa Ket"                "Ubon Ratchathani"        
[23] "Yasothon"                 "Chaiyaphum"              
[25] "Amnat Charoen"            "Nong Bua Lam Phu"        
[27] "Khon Kaen"                "Udon Thani"              
[29] "Loei"                     "Nong Khai"               
[31] "Maha Sarakham"            "Roi Et"                  
[33] "Kalasin"                  "Sakon Nakhon"            
[35] "Nakhon Phanom"            "Mukdahan"                
[37] "Chiang Mai"               "Lamphun"                 
[39] "Lampang"                  "Uttaradit"               
[41] "Phrae"                    "Nan"                     
[43] "Phayao"                   "Chiang Rai"              
[45] "Mae Hong Son"             "Nakhon Sawan"            
[47] "Uthai Thani"              "Kamphaeng Phet"          
[49] "Tak"                      "Sukhothai"               
[51] "Phitsanulok"              "Phichit"                 
[53] "Phetchabun"               "Ratchaburi"              
[55] "Kanchanaburi"             "Suphan Buri"             
[57] "Nakhon Pathom"            "Samut Sakhon"            
[59] "Samut Songkhram"          "Phetchaburi"             
[61] "Prachuap Khiri Khan"      "Nakhon Si Thammarat"     
[63] "Krabi"                    "Phangnga"                
[65] "Phuket"                   "Surat Thani"             
[67] "Ranong"                   "Chumphon"                
[69] "Songkhla"                 "Satun"                   
[71] "Trang"                    "Phatthalung"             
[73] "Pattani"                  "Yala"                    
[75] "Narathiwat"              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>unique_types</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "drug_use_cases"                                        
 [2] "suspects_in_drug_use_cases"                            
 [3] "possession_cases"                                      
 [4] "suspects_in_possession_cases"                          
 [5] "possession_with_intent_to_distribute_cases"            
 [6] "suspects_in_possession_with_intent_to_distribute_cases"
 [7] "trafficking_cases"                                     
 [8] "suspects_in_trafficking_cases"                         
 [9] "production_cases"                                      
[10] "suspects_in_production_cases"                          
[11] "import_cases"                                          
[12] "suspects_in_import_cases"                              
[13] "export_cases"                                          
[14] "suspects_in_export_cases"                              
[15] "conspiracy_cases"                                      
[16] "suspects_in_conspiracy_cases"                          </code></pre>
</div>
</div>
</section>
<section id="filtering-and-data-wrangling" class="level4">
<h4 class="anchored" data-anchor-id="filtering-and-data-wrangling">Filtering and Data Wrangling</h4>
<ul>
<li><p>As we are only interested in drug_cases under the types_of_drug_offenses, we need to filter based on that.</p></li>
<li><p>Lets drop both date and types_of_drug_offenses column, Sum all the no_cases by each year and province and sort them ascending, drop rows where the total_cases are 0.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>thailand <span class="ot">&lt;-</span> thailand_left_join_filtered <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"ADM1_EN"</span>, <span class="st">"fiscal_year"</span>, <span class="st">"types_of_drug_offenses"</span>, <span class="st">"no_cases"</span>, <span class="st">"geometry"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(types_of_drug_offenses <span class="sc">==</span> <span class="st">"drug_use_cases"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(no_cases <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(fiscal_year)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>thailand</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 450 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84
First 10 features:
                    ADM1_EN fiscal_year types_of_drug_offenses no_cases
1                   Bangkok        2017         drug_use_cases    11871
2              Samut Prakan        2017         drug_use_cases      820
3                Nonthaburi        2017         drug_use_cases      553
4              Pathum Thani        2017         drug_use_cases      450
5  Phra Nakhon Si Ayutthaya        2017         drug_use_cases      378
6                 Ang Thong        2017         drug_use_cases      208
7                 Sing Buri        2017         drug_use_cases      127
8                  Chai Nat        2017         drug_use_cases      200
9                  Saraburi        2017         drug_use_cases       69
10                Chon Buri        2017         drug_use_cases     4180
                         geometry
1  MULTIPOLYGON (((100.6139 13...
2  MULTIPOLYGON (((100.7306 13...
3  MULTIPOLYGON (((100.3415 14...
4  MULTIPOLYGON (((100.8916 14...
5  MULTIPOLYGON (((100.5131 14...
6  MULTIPOLYGON (((100.3332 14...
7  MULTIPOLYGON (((100.3691 15...
8  MULTIPOLYGON (((100.1199 15...
9  MULTIPOLYGON (((101.3994 15...
10 MULTIPOLYGON (((100.9719 12...</code></pre>
</div>
</div>
</section>
<section id="pivoting-the-fiscal-years-to-get-unique-polygons" class="level4">
<h4 class="anchored" data-anchor-id="pivoting-the-fiscal-years-to-get-unique-polygons">Pivoting the fiscal years to get unique Polygons</h4>
<ul>
<li>We do this because when we do polygonal rendering, there are 6 copies (years 2017-2022) of the same polygons, which will slow down the time it takes to execute the process such as the poly2nb() spatial weights when we attempt to find the neighbours of regions. Hence, we need to <strong>reshape</strong> the dataframe using pivot_wider() to <u>reduce the number of rows</u> (450/6 = 75), and make the <u>geometry polygons unique</u>, while keeping our provinces unique as well. This is done by transposing the fiscal_year and no_cases to more columns by the number of cases in each year (no_cases_&lt;year&gt;).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pivoting data to widen fiscal_year into separate no_cases columns by year</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>thailand <span class="ot">&lt;-</span> thailand <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ADM1_EN, geometry) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> fiscal_year, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> no_cases,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_prefix =</span> <span class="st">"no_cases_"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>thailand <span class="ot">&lt;-</span> thailand <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_cases =</span> no_cases_2017 <span class="sc">+</span> no_cases_2018 <span class="sc">+</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                     no_cases_2019 <span class="sc">+</span> no_cases_2020 <span class="sc">+</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                     no_cases_2021 <span class="sc">+</span> no_cases_2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="projection-transformation" class="level3">
<h3 class="anchored" data-anchor-id="projection-transformation">4.3 Projection Transformation</h3>
<p>Since the EPSG code is 4326, which is the global code. We want to change both the EPSG code of the boundary data and working data to Thailand’s global projection system. Acquiring the code from <a href="https://epsg.io/32647" class="uri">https://epsg.io/32647</a></p>
<ul>
<li>We will transform the it to Thailand’s projected coordinate system (UTM Zone 47N) with the EPSG code: 32647</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>thailand <span class="ot">&lt;-</span> thailand <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">32647</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(thailand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="plotting-the-shapefile-object-to-visualise-structure" class="level4">
<h4 class="anchored" data-anchor-id="plotting-the-shapefile-object-to-visualise-structure">4.3 Plotting the shapefile object to visualise structure</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>thailand_shp <span class="ot">=</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/tha_admbnda_adm1_rtsd_20220121.shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>boundary_plot <span class="ot">&lt;-</span> <span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(thailand_shp)<span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"white"</span>)<span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd=</span><span class="fl">0.3</span>, <span class="at">alpha=</span><span class="fl">0.6</span>)<span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title =</span> <span class="st">"Provinces"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.show =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">frame =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># basemap &lt;- tm_shape(thailand) +</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   tm_polygons() +</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   tm_text("ADM1_EN", size=0.5)</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># drug_cases &lt;- qtm(thailand, "no_cases")</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># tmap_arrange(basemap, drug_cases, asp=1, ncol=2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="writing-and-reading-into-rds-format" class="level4">
<h4 class="anchored" data-anchor-id="writing-and-reading-into-rds-format">4.4 Writing and Reading into RDS format</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#thailand combined dataframe</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(thailand, <span class="st">"data/rds/thailand.rds"</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># write_rds(boundary_plot, "data/rds/boundary_plot.rds")</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co"># write_rds(basemap, "data/rds/basemap.rds")</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># write_rds(drug_cases, "data/rds/drug_cases.rds")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>thailand <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/thailand.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
</section>
</section>
<section id="exploratory-spatial-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-spatial-data-analysis">5.0 Exploratory Spatial Data Analysis</h2>
<ul>
<li>min and max total no of drug cases</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>min_cases <span class="ot">=</span> <span class="fu">min</span>(thailand<span class="sc">$</span>no_cases, <span class="at">na.rm =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Unknown or uninitialised column: `no_cases`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(thailand$no_cases, na.rm = FALSE): no non-missing arguments to
min; returning Inf</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>max_cases <span class="ot">=</span> <span class="fu">max</span>(thailand<span class="sc">$</span>no_cases, <span class="at">na.rm =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Unknown or uninitialised column: `no_cases`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(thailand$no_cases, na.rm = FALSE): no non-missing arguments to
max; returning -Inf</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>min_cases</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Inf</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>max_cases</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -Inf</code></pre>
</div>
</div>
<section id="plotting" class="level3">
<h3 class="anchored" data-anchor-id="plotting">5.1 Plotting</h3>
</section>
<section id="total-number-of-cases-by-each-year-and-each-province" class="level3">
<h3 class="anchored" data-anchor-id="total-number-of-cases-by-each-year-and-each-province">5.1.1 Total number of cases by each year and each province</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>min_cases <span class="ot">&lt;-</span> <span class="fu">min</span>(thailand<span class="sc">$</span>no_cases_2017, thailand<span class="sc">$</span>no_cases_2018, thailand<span class="sc">$</span>no_cases_2019, </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                 thailand<span class="sc">$</span>no_cases_2020, thailand<span class="sc">$</span>no_cases_2021, thailand<span class="sc">$</span>no_cases_2022, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>max_cases <span class="ot">&lt;-</span> <span class="fu">max</span>(thailand<span class="sc">$</span>no_cases_2017, thailand<span class="sc">$</span>no_cases_2018, thailand<span class="sc">$</span>no_cases_2019, </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                 thailand<span class="sc">$</span>no_cases_2020, thailand<span class="sc">$</span>no_cases_2021, thailand<span class="sc">$</span>no_cases_2022, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define custom breaks based on the range</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>custom_breaks <span class="ot">&lt;-</span> <span class="fu">seq</span>(min_cases, max_cases, <span class="at">length.out =</span> <span class="dv">5</span>)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for 2017</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>plot_2017 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"no_cases_2017"</span>,</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> custom_breaks, </span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Drug Cases (2017)"</span>) <span class="sc">+</span></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"2017"</span>,  </span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">title.size =</span> <span class="fl">0.8</span>,     <span class="co"># Smaller title size</span></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>,  <span class="co"># Legend outside the map area</span></span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">asp =</span> <span class="fl">0.8</span>,              </span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.show =</span> <span class="cn">TRUE</span>)  <span class="co"># Show legend for only this plot</span></span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for 2018</span></span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>plot_2018 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"no_cases_2018"</span>,</span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> custom_breaks, </span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Drug Cases (2018)"</span>) <span class="sc">+</span></span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb51-31"><a href="#cb51-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"2018"</span>,  </span>
<span id="cb51-32"><a href="#cb51-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">title.size =</span> <span class="fl">0.8</span>,    </span>
<span id="cb51-33"><a href="#cb51-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">asp =</span> <span class="fl">0.8</span>,              </span>
<span id="cb51-34"><a href="#cb51-34" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-35"><a href="#cb51-35" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.show =</span> <span class="cn">FALSE</span>)  <span class="co"># Hide legend</span></span>
<span id="cb51-36"><a href="#cb51-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-37"><a href="#cb51-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for 2019</span></span>
<span id="cb51-38"><a href="#cb51-38" aria-hidden="true" tabindex="-1"></a>plot_2019 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb51-39"><a href="#cb51-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"no_cases_2019"</span>,</span>
<span id="cb51-40"><a href="#cb51-40" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb51-41"><a href="#cb51-41" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> custom_breaks, </span>
<span id="cb51-42"><a href="#cb51-42" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Drug Cases (2019)"</span>) <span class="sc">+</span></span>
<span id="cb51-43"><a href="#cb51-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb51-44"><a href="#cb51-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"2019"</span>,  </span>
<span id="cb51-45"><a href="#cb51-45" aria-hidden="true" tabindex="-1"></a>            <span class="at">title.size =</span> <span class="fl">0.8</span>,     </span>
<span id="cb51-46"><a href="#cb51-46" aria-hidden="true" tabindex="-1"></a>            <span class="at">asp =</span> <span class="fl">0.8</span>,              </span>
<span id="cb51-47"><a href="#cb51-47" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-48"><a href="#cb51-48" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.show =</span> <span class="cn">FALSE</span>)  <span class="co"># Hide legend</span></span>
<span id="cb51-49"><a href="#cb51-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-50"><a href="#cb51-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for 2020</span></span>
<span id="cb51-51"><a href="#cb51-51" aria-hidden="true" tabindex="-1"></a>plot_2020 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb51-52"><a href="#cb51-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"no_cases_2020"</span>,</span>
<span id="cb51-53"><a href="#cb51-53" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb51-54"><a href="#cb51-54" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> custom_breaks, </span>
<span id="cb51-55"><a href="#cb51-55" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Drug Cases (2020)"</span>) <span class="sc">+</span></span>
<span id="cb51-56"><a href="#cb51-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb51-57"><a href="#cb51-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"2020"</span>,  </span>
<span id="cb51-58"><a href="#cb51-58" aria-hidden="true" tabindex="-1"></a>            <span class="at">title.size =</span> <span class="fl">0.8</span>,     </span>
<span id="cb51-59"><a href="#cb51-59" aria-hidden="true" tabindex="-1"></a>            <span class="at">asp =</span> <span class="fl">0.8</span>,              </span>
<span id="cb51-60"><a href="#cb51-60" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-61"><a href="#cb51-61" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.show =</span> <span class="cn">FALSE</span>)  <span class="co"># Hide legend</span></span>
<span id="cb51-62"><a href="#cb51-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-63"><a href="#cb51-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for 2021</span></span>
<span id="cb51-64"><a href="#cb51-64" aria-hidden="true" tabindex="-1"></a>plot_2021 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb51-65"><a href="#cb51-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"no_cases_2021"</span>,</span>
<span id="cb51-66"><a href="#cb51-66" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb51-67"><a href="#cb51-67" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> custom_breaks, </span>
<span id="cb51-68"><a href="#cb51-68" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Drug Cases (2021)"</span>) <span class="sc">+</span></span>
<span id="cb51-69"><a href="#cb51-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb51-70"><a href="#cb51-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"2021"</span>,  </span>
<span id="cb51-71"><a href="#cb51-71" aria-hidden="true" tabindex="-1"></a>            <span class="at">title.size =</span> <span class="fl">0.8</span>,     </span>
<span id="cb51-72"><a href="#cb51-72" aria-hidden="true" tabindex="-1"></a>            <span class="at">asp =</span> <span class="fl">0.8</span>,              </span>
<span id="cb51-73"><a href="#cb51-73" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-74"><a href="#cb51-74" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.show =</span> <span class="cn">FALSE</span>)  <span class="co"># Hide legend</span></span>
<span id="cb51-75"><a href="#cb51-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-76"><a href="#cb51-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for 2022</span></span>
<span id="cb51-77"><a href="#cb51-77" aria-hidden="true" tabindex="-1"></a>plot_2022 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb51-78"><a href="#cb51-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"no_cases_2022"</span>,</span>
<span id="cb51-79"><a href="#cb51-79" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb51-80"><a href="#cb51-80" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> custom_breaks, </span>
<span id="cb51-81"><a href="#cb51-81" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Drug Cases (2022)"</span>) <span class="sc">+</span></span>
<span id="cb51-82"><a href="#cb51-82" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb51-83"><a href="#cb51-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"2022"</span>,  </span>
<span id="cb51-84"><a href="#cb51-84" aria-hidden="true" tabindex="-1"></a>            <span class="at">title.size =</span> <span class="fl">0.8</span>,     </span>
<span id="cb51-85"><a href="#cb51-85" aria-hidden="true" tabindex="-1"></a>            <span class="at">asp =</span> <span class="fl">0.8</span>,              </span>
<span id="cb51-86"><a href="#cb51-86" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-87"><a href="#cb51-87" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.show =</span> <span class="cn">FALSE</span>)  <span class="co"># Hide legend</span></span>
<span id="cb51-88"><a href="#cb51-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-89"><a href="#cb51-89" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange all plots side by side in a grid with one legend</span></span>
<span id="cb51-90"><a href="#cb51-90" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(plot_2017, plot_2018, plot_2019, plot_2020, plot_2021, plot_2022, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Legend labels were too wide. The labels have been resized to 0.07, 0.05, 0.05, 0.04. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).
Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).
Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).
Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).
Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="side-by-side-view-of-province-and-total-no-of-drug-cases-in-year-2017" class="level3">
<h3 class="anchored" data-anchor-id="side-by-side-view-of-province-and-total-no-of-drug-cases-in-year-2017">5.1.2 Side by side view of province and total no of drug cases in year 2017</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># provinces &lt;- tm_shape(thailand %&gt;% filter(fiscal_year == 2017)) +</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   tm_polygons() +</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   tm_text("ADM1_EN", size=0.5)</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="co"># custom_breaks &lt;- c(0, 5000, 10000, 15000, 20000)  # Customize as necessary</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># # total_cases &lt;- qtm(thailand_summary, "total_cases")</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="co"># no_cases &lt;- tm_shape(thailand) +</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   tm_polygons("no_cases", </span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="co">#               breaks = custom_breaks,  # Apply the custom breaks</span></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="co">#               palette = "Blues",        # Color palette</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="co">#               title = "Number of Cases")    # Title for the legend</span></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="co"># tmap_arrange(provinces, no_cases, asp=1, ncol=2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="top-5-provinces-with-the-highest-number-of-drug-cases-over-all-the-years" class="level3">
<h3 class="anchored" data-anchor-id="top-5-provinces-with-the-highest-number-of-drug-cases-over-all-the-years">5.1.3 Top 5 Provinces with the highest number of drug cases over all the years</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Find the top 5 provinces with the highest total cases</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>top_5_provinces <span class="ot">&lt;-</span> thailand <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_cases)) <span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>)  <span class="co"># Select the top 5 rows</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Highlight the top 5 provinces</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>provinces <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"ADM1_EN"</span>, <span class="at">size =</span> <span class="fl">0.5</span>)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply custom breaks to the total_cases plot</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>total_cases <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"total_cases"</span>,</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">breaks =</span> custom_breaks,  <span class="co"># Apply the custom breaks</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Blues"</span>,        <span class="co"># Color palette</span></span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Total Cases"</span>) <span class="sc">+</span></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Highlight the top 5 provinces on the same plot</span></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>highlight_top_5 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(top_5_provinces) <span class="sc">+</span></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span>  <span class="co"># Use red borders to highlight</span></span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"ADM1_EN"</span>, <span class="at">size =</span> <span class="fl">0.7</span>, <span class="at">col =</span> <span class="st">"black"</span>)  <span class="co"># Optional: Label them</span></span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Arrange the plots</span></span>
<span id="cb56-25"><a href="#cb56-25" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(provinces, total_cases <span class="sc">+</span> highlight_top_5, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Values have found that are higher than the highest break</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visualising-equal-and-quantile-over-all-the-years" class="level3">
<h3 class="anchored" data-anchor-id="visualising-equal-and-quantile-over-all-the-years">5.2 Visualising Equal and Quantile over all the years</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>equal <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"total_cases"</span>,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style=</span><span class="st">"equal"</span>, <span class="at">n=</span><span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal interval classification"</span>, <span class="at">title.size =</span> <span class="dv">2</span>)</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>quantile <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand) <span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"total_cases"</span>,</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">style=</span><span class="st">"quantile"</span>, <span class="at">n=</span><span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Quantile interval classification"</span>, <span class="at">title.size =</span> <span class="dv">2</span>)</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(equal,</span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>             quantile,</span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>,</span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One tm layer group has duplicated layer types, which are omitted. To
draw multiple layers of the same type, use multiple layer groups (i.e. specify
tm_shape prior to each of them).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="global-measures-of-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="global-measures-of-spatial-autocorrelation">6.0 Global Measures of Spatial Autocorrelation</h2>
<ul>
<li>If we attempt to use contiguity-based spatial weights to find neighbours, and use the queen method, we come up with a region that is not linked to any neighbours, which is incorrect. Hence, we need to swap to using distance-based method to find neighbours.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(thailand, </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">queen =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in poly2nb(thailand, queen = TRUE): some observations have no neighbours;
if this seems unexpected, try increasing the snap argument.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in poly2nb(thailand, queen = TRUE): neighbour object has 2 sub-graphs;
if this sub-graph count seems unexpected, try increasing the snap argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 75 
Number of nonzero links: 330 
Percentage nonzero weights: 5.866667 
Average number of links: 4.4 
1 region with no links:
65
2 disjoint connected subgraphs
Link number distribution:

 0  1  2  3  4  5  6  7  8  9 
 1  1  6 18 14 16 11  5  1  2 
1 least connected region:
13 with 1 link
2 most connected regions:
27 49 with 9 links</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(wm_q, <span class="st">"data/rds/wm_q.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/wm_q.rds"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 75 
Number of nonzero links: 330 
Percentage nonzero weights: 5.866667 
Average number of links: 4.4 
1 region with no links:
65
2 disjoint connected subgraphs
Link number distribution:

 0  1  2  3  4  5  6  7  8  9 
 1  1  6 18 14 16 11  5  1  2 
1 least connected region:
13 with 1 link
2 most connected regions:
27 49 with 9 links</code></pre>
</div>
</div>
<p><em>nb2listw()</em> is used to convert the nb object into spatial weights object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>rswm_q <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">style=</span><span class="st">"W"</span>, </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>rswm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 75 
Number of nonzero links: 330 
Percentage nonzero weights: 5.866667 
Average number of links: 4.4 
1 region with no links:
65
2 disjoint connected subgraphs

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 74 5476 74 36.37549 308.5545</code></pre>
</div>
</div>
<section id="configuring-and-binding-coordinates" class="level3">
<h3 class="anchored" data-anchor-id="configuring-and-binding-coordinates">6.1 Configuring and Binding coordinates</h3>
<section id="computing-longitude-and-latitude-to-achieve-coordinates" class="level4">
<h4 class="anchored" data-anchor-id="computing-longitude-and-latitude-to-achieve-coordinates">Computing longitude and latitude to achieve coordinates</h4>
<ul>
<li>longitude</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(thailand<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>latitude</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(thailand<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>bind the coordinates</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude latitude
[1,]  675514.6  1523087
[2,]  685033.7  1503755
[3,]  650477.2  1539777
[4,]  681656.0  1555581
[5,]  664627.1  1586462
[6,]  645239.0  1617118</code></pre>
</div>
</div>
</section>
</section>
<section id="computing-distance-based-neighbours" class="level3">
<h3 class="anchored" data-anchor-id="computing-distance-based-neighbours">6.2 Computing distance-based neighbours</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>k1 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in knn2nb(knearneigh(coords)): neighbour object has 19 sub-graphs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>k1dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">nbdists</span>(k1, coords, <span class="at">longlat =</span> <span class="cn">FALSE</span>))</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  21548   50601   64530   63106   76823  110987 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
This summary report shows that the largest first nearest neighbour distance is 110987 meters (UTM). As dnearneigh accepts meters and we need specify longlat = FALSE, lets round it up to 111000 meters and use this as our upper threshold will ensure us that all regions will at least have 1 neighbour.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
</section>
<section id="fixed-distance" class="level3">
<h3 class="anchored" data-anchor-id="fixed-distance">6.2.1 Fixed Distance</h3>
<ul>
<li>within 111000 meters radius</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>wm_d111000 <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span>, <span class="dv">111000</span>, <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dnearneigh(coords, 0, 111000, longlat = FALSE): neighbour object has
2 sub-graphs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>wm_d111000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 75 
Number of nonzero links: 332 
Percentage nonzero weights: 5.902222 
Average number of links: 4.426667 
2 disjoint connected subgraphs</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(thailand<span class="sc">$</span>ADM1_EN, <span class="fu">card</span>(wm_d111000))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          
                           1 2 3 4 5 6 8 9 10 12 13 14
  amnat charoen            0 0 0 1 0 0 0 0  0  0  0  0
  ang thong                0 0 0 0 0 0 0 0  1  0  0  0
  bangkok                  0 0 0 0 0 0 0 0  0  1  0  0
  buri ram                 0 1 0 0 0 0 0 0  0  0  0  0
  chachoengsao             0 0 0 0 0 0 0 1  0  0  0  0
  chai nat                 0 0 0 0 0 1 0 0  0  0  0  0
  chaiyaphum               0 1 0 0 0 0 0 0  0  0  0  0
  chanthaburi              0 0 0 0 1 0 0 0  0  0  0  0
  chiang mai               0 0 1 0 0 0 0 0  0  0  0  0
  chiang rai               1 0 0 0 0 0 0 0  0  0  0  0
  chon buri                0 0 0 0 0 1 0 0  0  0  0  0
  chumphon                 1 0 0 0 0 0 0 0  0  0  0  0
  kalasin                  0 0 0 1 0 0 0 0  0  0  0  0
  kamphaeng phet           0 0 0 0 1 0 0 0  0  0  0  0
  kanchanaburi             0 1 0 0 0 0 0 0  0  0  0  0
  khon kaen                0 0 1 0 0 0 0 0  0  0  0  0
  krabi                    0 0 0 0 1 0 0 0  0  0  0  0
  lampang                  0 0 1 0 0 0 0 0  0  0  0  0
  lamphun                  0 1 0 0 0 0 0 0  0  0  0  0
  loei                     1 0 0 0 0 0 0 0  0  0  0  0
  mae hong son             1 0 0 0 0 0 0 0  0  0  0  0
  maha sarakham            0 0 1 0 0 0 0 0  0  0  0  0
  mukdahan                 0 0 0 0 1 0 0 0  0  0  0  0
  nakhon nayok             0 0 0 0 0 0 0 1  0  0  0  0
  nakhon pathom            0 0 0 0 0 0 0 0  1  0  0  0
  nakhon phanom            0 1 0 0 0 0 0 0  0  0  0  0
  nakhon ratchasima        1 0 0 0 0 0 0 0  0  0  0  0
  nakhon sawan             0 0 0 0 1 0 0 0  0  0  0  0
  nakhon si thammarat      0 0 0 1 0 0 0 0  0  0  0  0
  nan                      0 1 0 0 0 0 0 0  0  0  0  0
  narathiwat               0 1 0 0 0 0 0 0  0  0  0  0
  nong bua lam phu         0 0 0 1 0 0 0 0  0  0  0  0
  nong khai                0 1 0 0 0 0 0 0  0  0  0  0
  nonthaburi               0 0 0 0 0 0 0 0  0  0  1  0
  pathum thani             0 0 0 0 0 0 0 0  0  0  0  1
  pattani                  0 0 1 0 0 0 0 0  0  0  0  0
  phangnga                 0 0 1 0 0 0 0 0  0  0  0  0
  phatthalung              0 0 0 1 0 0 0 0  0  0  0  0
  phayao                   0 1 0 0 0 0 0 0  0  0  0  0
  phetchabun               0 0 1 0 0 0 0 0  0  0  0  0
  phetchaburi              0 0 0 1 0 0 0 0  0  0  0  0
  phichit                  0 0 0 1 0 0 0 0  0  0  0  0
  phitsanulok              0 0 0 1 0 0 0 0  0  0  0  0
  phra nakhon si ayutthaya 0 0 0 0 0 0 0 0  0  1  0  0
  phrae                    0 0 0 1 0 0 0 0  0  0  0  0
  phuket                   0 1 0 0 0 0 0 0  0  0  0  0
  prachin buri             0 0 0 0 0 1 0 0  0  0  0  0
  prachuap khiri khan      1 0 0 0 0 0 0 0  0  0  0  0
  ranong                   0 1 0 0 0 0 0 0  0  0  0  0
  ratchaburi               0 0 0 0 1 0 0 0  0  0  0  0
  rayong                   0 0 1 0 0 0 0 0  0  0  0  0
  roi et                   0 0 0 0 1 0 0 0  0  0  0  0
  sa kaeo                  0 0 1 0 0 0 0 0  0  0  0  0
  sakon nakhon             0 0 1 0 0 0 0 0  0  0  0  0
  samut prakan             0 0 0 0 0 0 0 0  1  0  0  0
  samut sakhon             0 0 0 0 0 0 0 1  0  0  0  0
  samut songkhram          0 0 0 0 0 0 1 0  0  0  0  0
  saraburi                 0 0 0 0 0 0 1 0  0  0  0  0
  satun                    0 0 1 0 0 0 0 0  0  0  0  0
  si sa ket                0 1 0 0 0 0 0 0  0  0  0  0
  sing buri                0 0 0 0 0 0 0 1  0  0  0  0
  songkhla                 0 0 1 0 0 0 0 0  0  0  0  0
  sukhothai                0 0 0 1 0 0 0 0  0  0  0  0
  suphan buri              0 0 0 0 0 0 0 1  0  0  0  0
  surat thani              0 0 0 1 0 0 0 0  0  0  0  0
  surin                    0 1 0 0 0 0 0 0  0  0  0  0
  tak                      1 0 0 0 0 0 0 0  0  0  0  0
  trang                    0 0 0 1 0 0 0 0  0  0  0  0
  trat                     1 0 0 0 0 0 0 0  0  0  0  0
  ubon ratchathani         0 1 0 0 0 0 0 0  0  0  0  0
  udon thani               0 0 1 0 0 0 0 0  0  0  0  0
  uthai thani              0 0 0 0 0 1 0 0  0  0  0  0
  uttaradit                0 0 1 0 0 0 0 0  0  0  0  0
  yala                     0 1 0 0 0 0 0 0  0  0  0  0
  yasothon                 0 0 1 0 0 0 0 0  0  0  0  0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>n_comp <span class="ot">&lt;-</span> <span class="fu">n.comp.nb</span>(wm_d111000)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>n_comp<span class="sc">$</span>nc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<ul>
<li>This shows that there are 2 different clusters, meaning that some regions are connected to each other, while others are not, leading to two distinct groups. Below shows that the first cluster contains 61 regions, while the second cluster contains 14 regions.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(n_comp<span class="sc">$</span>comp.id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2 
61 14 </code></pre>
</div>
</div>
<section id="plotting-fixed-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="plotting-fixed-distance-weight-matrix">Plotting fixed distance weight matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>x_limits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(longitude) <span class="sc">-</span> <span class="dv">1000</span>, <span class="fu">max</span>(longitude) <span class="sc">+</span> <span class="dv">1000</span>)  <span class="co"># Adjust these values as needed</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>y_limits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(latitude) <span class="sc">-</span> <span class="dv">1000</span>, <span class="fu">max</span>(latitude) <span class="sc">+</span> <span class="dv">1000</span>)   <span class="co"># Adjust these values as needed</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the boundary and neighborhood structures with adjusted limits</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thailand<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">xlim =</span> x_limits, <span class="at">ylim =</span> y_limits)</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d111000, coords, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Plot 1st nearest neighbours (red lines) vs Distance link of neighbours within the cut-off distance of 111000 meters (black lines)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thailand<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"1st nearest neighbours"</span>)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thailand<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Distance link"</span>)</span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d111000, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="adaptive-distance" class="level3">
<h3 class="anchored" data-anchor-id="adaptive-distance">6.2.2 Adaptive Distance</h3>
<section id="computing-adaptive-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="computing-adaptive-distance-weight-matrix">Computing Adaptive Distance Weight matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>knn6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">6</span>))</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 75 
Number of nonzero links: 450 
Percentage nonzero weights: 8 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 75
 $ : int [1:6] 2 3 4 5 57 58
 $ : int [1:6] 1 3 4 10 57 58
 $ : int [1:6] 1 2 4 5 57 58
 $ : int [1:6] 1 2 3 5 16 57
 $ : int [1:6] 1 3 4 6 9 57
 $ : int [1:6] 4 5 7 8 9 56
 $ : int [1:6] 5 6 8 9 46 56
 $ : int [1:6] 5 6 7 46 47 56
 $ : int [1:6] 4 5 6 7 15 16
 $ : int [1:6] 1 2 11 12 14 15
 $ : int [1:6] 1 2 10 12 13 14
 $ : int [1:6] 10 11 13 14 15 17
 $ : int [1:6] 10 11 12 14 15 17
 $ : int [1:6] 1 2 10 11 15 16
 $ : int [1:6] 4 9 10 14 16 17
 $ : int [1:6] 1 4 5 9 14 15
 $ : int [1:6] 12 14 15 16 18 19
 $ : int [1:6] 9 15 16 17 19 24
 $ : int [1:6] 17 18 20 21 31 32
 $ : int [1:6] 19 21 22 23 31 32
 $ : int [1:6] 19 20 22 23 25 32
 $ : int [1:6] 20 21 23 25 32 36
 $ : int [1:6] 21 22 25 32 33 36
 $ : int [1:6] 18 26 27 29 31 53
 $ : int [1:6] 21 22 23 32 33 36
 $ : int [1:6] 24 27 28 29 30 33
 $ : int [1:6] 24 26 28 31 32 33
 $ : int [1:6] 26 27 29 30 33 34
 $ : int [1:6] 26 28 30 40 51 53
 $ : int [1:6] 26 27 28 29 33 34
 $ : int [1:6] 19 20 23 27 32 33
 $ : int [1:6] 20 23 25 31 33 36
 $ : int [1:6] 23 27 31 32 34 36
 $ : int [1:6] 28 30 32 33 35 36
 $ : int [1:6] 23 25 28 33 34 36
 $ : int [1:6] 23 25 32 33 34 35
 $ : int [1:6] 38 39 41 43 44 45
 $ : int [1:6] 37 39 41 45 49 50
 $ : int [1:6] 37 38 40 41 43 50
 $ : int [1:6] 29 39 41 42 50 51
 $ : int [1:6] 38 39 40 42 43 50
 $ : int [1:6] 29 39 40 41 43 44
 $ : int [1:6] 37 39 40 41 42 44
 $ : int [1:6] 37 38 39 41 42 43
 $ : int [1:6] 37 38 39 41 43 44
 $ : int [1:6] 6 7 8 47 48 52
 $ : int [1:6] 7 8 46 48 55 56
 $ : int [1:6] 46 47 49 50 51 52
 $ : int [1:6] 38 46 47 48 50 52
 $ : int [1:6] 39 40 41 48 49 51
 $ : int [1:6] 29 40 48 50 52 53
 $ : int [1:6] 8 46 48 50 51 53
 $ : int [1:6] 24 27 29 46 51 52
 $ : int [1:6] 1 3 57 58 59 60
 $ : int [1:6] 6 8 47 54 56 57
 $ : int [1:6] 5 6 7 8 55 57
 $ : int [1:6] 1 3 4 5 58 59
 $ : int [1:6] 1 2 3 54 57 59
 $ : int [1:6] 1 3 54 57 58 60
 $ : int [1:6] 3 54 57 58 59 61
 $ : int [1:6] 2 54 58 59 60 68
 $ : int [1:6] 63 64 65 66 71 72
 $ : int [1:6] 62 64 65 66 71 72
 $ : int [1:6] 62 63 65 66 67 71
 $ : int [1:6] 62 63 64 66 71 72
 $ : int [1:6] 62 63 64 65 67 68
 $ : int [1:6] 62 63 64 65 66 68
 $ : int [1:6] 61 62 63 64 66 67
 $ : int [1:6] 70 71 72 73 74 75
 $ : int [1:6] 62 69 71 72 73 74
 $ : int [1:6] 62 63 65 69 70 72
 $ : int [1:6] 62 63 69 70 71 73
 $ : int [1:6] 69 70 71 72 74 75
 $ : int [1:6] 69 70 71 72 73 75
 $ : int [1:6] 69 70 71 72 73 74
 - attr(*, "region.id")= chr [1:75] "1" "2" "3" "4" ...
 - attr(*, "call")= language knearneigh(x = coords, k = 6)
 - attr(*, "sym")= logi FALSE
 - attr(*, "type")= chr "knn"
 - attr(*, "knn-k")= num 6
 - attr(*, "class")= chr "nb"
 - attr(*, "ncomp")=List of 2
  ..$ nc     : int 1
  ..$ comp.id: int [1:75] 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(thailand<span class="sc">$</span>ADM1_EN, <span class="fu">card</span>(knn6))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          
                           6
  amnat charoen            1
  ang thong                1
  bangkok                  1
  buri ram                 1
  chachoengsao             1
  chai nat                 1
  chaiyaphum               1
  chanthaburi              1
  chiang mai               1
  chiang rai               1
  chon buri                1
  chumphon                 1
  kalasin                  1
  kamphaeng phet           1
  kanchanaburi             1
  khon kaen                1
  krabi                    1
  lampang                  1
  lamphun                  1
  loei                     1
  mae hong son             1
  maha sarakham            1
  mukdahan                 1
  nakhon nayok             1
  nakhon pathom            1
  nakhon phanom            1
  nakhon ratchasima        1
  nakhon sawan             1
  nakhon si thammarat      1
  nan                      1
  narathiwat               1
  nong bua lam phu         1
  nong khai                1
  nonthaburi               1
  pathum thani             1
  pattani                  1
  phangnga                 1
  phatthalung              1
  phayao                   1
  phetchabun               1
  phetchaburi              1
  phichit                  1
  phitsanulok              1
  phra nakhon si ayutthaya 1
  phrae                    1
  phuket                   1
  prachin buri             1
  prachuap khiri khan      1
  ranong                   1
  ratchaburi               1
  rayong                   1
  roi et                   1
  sa kaeo                  1
  sakon nakhon             1
  samut prakan             1
  samut sakhon             1
  samut songkhram          1
  saraburi                 1
  satun                    1
  si sa ket                1
  sing buri                1
  songkhla                 1
  sukhothai                1
  suphan buri              1
  surat thani              1
  surin                    1
  tak                      1
  trang                    1
  trat                     1
  ubon ratchathani         1
  udon thani               1
  uthai thani              1
  uttaradit                1
  yala                     1
  yasothon                 1</code></pre>
</div>
</div>
</section>
<section id="plotting-adaptive-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="plotting-adaptive-distance-weight-matrix">Plotting adaptive distance weight matrix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(thailand<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(knn6, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="global-moran-i-access-spatial-autocorrelation-using-adaptive-distance" class="level3">
<h3 class="anchored" data-anchor-id="global-moran-i-access-spatial-autocorrelation-using-adaptive-distance">6.2.3 Global Moran I: Access Spatial Autocorrelation using Adaptive Distance</h3>
<p>Next, <em>nb2listw()</em> is used to convert the nb object into spatial weights object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>rsknn6 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn6, </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">style=</span><span class="st">"W"</span>, </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>rsknn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 75 
Number of nonzero links: 450 
Percentage nonzero weights: 8 
Average number of links: 6 
Non-symmetric neighbours list

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 75 5625 75 22.27778 311.6667</code></pre>
</div>
</div>
<section id="global-morans-i-test" class="level4">
<h4 class="anchored" data-anchor-id="global-morans-i-test">1. Global Moran’s I Test</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(thailand<span class="sc">$</span>total_cases, </span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw=</span>rsknn6, </span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  thailand$total_cases  
weights: rsknn6    

Moran I statistic standard deviate = 1.4928, p-value = 0.06774
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
       0.07005720       -0.01351351        0.00313397 </code></pre>
</div>
</div>
</section>
<section id="computing-monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="computing-monte-carlo-morans-i">2. .Computing Monte Carlo Moran’s I</h4>
<ul>
<li><p>set a seed of 1234</p></li>
<li><p>number of simulations = 1000</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>bperm_moran<span class="ot">=</span> <span class="fu">moran.mc</span>(thailand<span class="sc">$</span>total_cases, </span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">listw=</span>rsknn6, </span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">999</span>, </span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action=</span>na.omit)</span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>bperm_moran</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  thailand$total_cases 
weights: rsknn6  
number of simulations + 1: 1000 

statistic = 0.070057, observed rank = 909, p-value = 0.091
alternative hypothesis: greater</code></pre>
</div>
</div>
<ul>
<li><p>moran I statistic: 0.070057 &gt; 0 show signs of clustering</p></li>
<li><p>p-value = 0.091 &gt; 0.05, 95% confident to accept null hypothesis (h0)</p></li>
</ul>
</section>
<section id="visualising-monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="visualising-monte-carlo-morans-i">3. Visualising Monte Carlo Moran’s I</h4>
<ul>
<li>Computing some basic statistics</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute mean</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bperm_moran<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.01000913</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute variance</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(bperm_moran<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00319814</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary bperm</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bperm_moran<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-0.15423 -0.05047 -0.01599 -0.01001  0.02541  0.22929 </code></pre>
</div>
</div>
<ul>
<li>plotting histogram using ggplot2</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">simulated_morans_i =</span> bperm_moran<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> simulated_morans_i)) <span class="sc">+</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> (<span class="fu">max</span>(data<span class="sc">$</span>simulated_morans_i) <span class="sc">-</span> <span class="fu">min</span>(data<span class="sc">$</span>simulated_morans_i)) <span class="sc">/</span> <span class="dv">20</span>, </span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"pink"</span>) <span class="sc">+</span>  <span class="co"># Histogram</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>) <span class="sc">+</span>  <span class="co"># Vertical line at x=0</span></span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Simulated Moran's I"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span>  <span class="co"># Labels for x and y axis</span></span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  <span class="co"># Clean minimal theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="spatial-correlogram" class="level3">
<h3 class="anchored" data-anchor-id="spatial-correlogram">6.3 Spatial Correlogram</h3>
<section id="compute-morans-i-spatial-correlogram" class="level4">
<h4 class="anchored" data-anchor-id="compute-morans-i-spatial-correlogram">Compute Moran’s I Spatial Correlogram</h4>
<p>In the code chunk below,&nbsp;<a href="https://r-spatial.github.io/spdep/reference/sp.correlogram.html"><code>sp.correlogram()</code></a>&nbsp;of&nbsp;<strong>spdep</strong>&nbsp;package is used to compute a <u><strong>6-lag</strong></u> spatial correlogram of GDPPC. The global spatial autocorrelation used in Moran’s I. The&nbsp;<strong>plot()</strong>&nbsp;of base Graph is then used to plot the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>MI_corr <span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(knn6,                            </span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>                          thailand<span class="sc">$</span>total_cases,</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">order=</span><span class="dv">6</span>,  <span class="co">#lag-value: 6                           </span></span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method=</span><span class="st">"I"</span>,                            </span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">style=</span><span class="st">"W"</span>,</span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">zero.policy =</span> <span class="cn">TRUE</span>) </span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-8"><a href="#cb114-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Looking at the first lag, it is positive, showing signs of clustering. This suggests that the the key indicators of drug abuse of Thailand have positive spatial dependence. The following lags after shows negative Moran I, showing signs of regular patterns amongst 2nd order neighbours and below.</li>
</ul>
<p>By plotting the output might not allow us to provide complete interpretation. This is because not all autocorrelation values are statistically significant. Hence, it is important for us to examine the full analysis report by printing out the analysis results as in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatial correlogram for thailand$total_cases 
method: Moran's I
         estimate expectation   variance standard deviate Pr(I) two sided  
1 (75)  0.0700572  -0.0135135  0.0031340           1.4928         0.13548  
2 (75) -0.0540624  -0.0135135  0.0023706          -0.8328         0.40494  
3 (75) -0.0060335  -0.0135135  0.0022208           0.1587         0.87388  
4 (75) -0.0500771  -0.0135135  0.0020147          -0.8146         0.41530  
5 (75)  0.0242813  -0.0135135  0.0019363           0.8589         0.39039  
6 (75) -0.1007630  -0.0135135  0.0019960          -1.9529         0.05083 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="local-measures-of-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="local-measures-of-spatial-autocorrelation">7.0 Local Measures of Spatial Autocorrelation</h2>
<p>Because of non-linked regions such as Phuket, we cannot use Queen and Rook methods to access local spatial autocorrelation, as it may lead to inaccuracies in the analysis. We need to use fixed-distance and adaptive-distance based methods for more reliable results.</p>
<p>We will detect the clusters, outliers, and hotspots using</p>
<ul>
<li><p><em>Getis-Ord G (Gi) Statistics:</em> Detect hotspots and clusters</p>
<ul>
<li><p>Deriving spatial weight matrix</p></li>
<li><p>Computing Gi statistics</p></li>
<li><p>Mapping Gi statistics</p></li>
</ul></li>
<li><p>Local Moran’s I: Detect local clusters (high-high and low-low) and local outliers (high-low, low-high)</p></li>
</ul>
<section id="fixed-distance-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="fixed-distance-weight-matrix">7.1 Fixed Distance Weight Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>wm_d111000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 75 
Number of nonzero links: 332 
Percentage nonzero weights: 5.902222 
Average number of links: 4.426667 
2 disjoint connected subgraphs</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>wm_d111000_lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_d111000, <span class="at">style =</span> <span class="st">'B'</span>)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_d111000_lw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 75 
Number of nonzero links: 332 
Percentage nonzero weights: 5.902222 
Average number of links: 4.426667 
2 disjoint connected subgraphs
Link number distribution:

 1  2  3  4  5  6  8  9 10 12 13 14 
 8 15 15 12  7  4  2  5  3  2  1  1 
8 least connected regions:
13 18 29 44 45 49 61 68 with 1 link
1 most connected region:
4 with 14 links

Weights style: B 
Weights constants summary:
   n   nn  S0  S1   S2
B 75 5625 332 664 8800</code></pre>
</div>
</div>
</section>
<section id="adaptive-distance-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="adaptive-distance-weight-matrix">7.2 Adaptive Distance Weight Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>knn8 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">8</span>))</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>knn8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 75 
Number of nonzero links: 600 
Percentage nonzero weights: 10.66667 
Average number of links: 8 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<p>Next,&nbsp;<em>nb2listw()</em>&nbsp;is used to convert the nb object into spatial weights object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>knn8_lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn8, <span class="at">style =</span> <span class="st">'B'</span>)</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(knn8_lw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 75 
Number of nonzero links: 600 
Percentage nonzero weights: 10.66667 
Average number of links: 8 
Non-symmetric neighbours list
Link number distribution:

 8 
75 
75 least connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 with 8 links
75 most connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 with 8 links

Weights style: B 
Weights constants summary:
   n   nn  S0   S1    S2
B 75 5625 600 1068 19930</code></pre>
</div>
</div>
<p>Here, we can see that all 75 provinces have exactly 8 links, and province like Phuket are not left behind.</p>
</section>
<section id="computing-gi-statistics" class="level3">
<h3 class="anchored" data-anchor-id="computing-gi-statistics">7.3 Computing Gi Statistics</h3>
<p>Next, we need to perform Gi Statistics, for each fixed distance and adaptive distances. The computed Gi statistic will give us a representation of a Z-score. Greater <u><strong>local Gi</strong></u> represent a greater intensity of <strong>clustering</strong> and the direction (positive or negative) indicates <strong>high or low clusters.</strong></p>
</section>
<section id="gi-statistics-for-fixed-distance" class="level3">
<h3 class="anchored" data-anchor-id="gi-statistics-for-fixed-distance">7.3.1 Gi statistics for fixed distance</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(thailand<span class="sc">$</span>ADM1_EN)</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>gi.fixed <span class="ot">&lt;-</span> <span class="fu">localG</span>(thailand<span class="sc">$</span>total_cases, wm_d111000_lw)</span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>gi.fixed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -0.201153316  1.739088527  0.045644666 -0.022941247 -0.017795896
 [6]  0.387808639 -1.827279180 -1.682632988  0.791582358  3.039231470
[11]  1.634023502  1.459721351 -0.253452096  2.898901739  0.616659283
[16]  1.142944501 -0.019835157  0.438556285  0.985988570  0.940721263
[21]  1.712739354  0.689067156  0.106475550  0.624829738  1.323430679
[26]  0.584664818 -0.486169659 -0.746449363 -0.953827643 -0.488137883
[31]  0.771358900 -0.141327546 -0.343189680 -0.028190065 -0.275555366
[36]  0.004799014 -0.495041124  1.573420726  1.144973857 -0.782343385
[41] -0.734644388 -0.134981141  0.567452280 -0.158095152  2.053028860
[46] -1.739363723 -1.507307891 -1.589371187 -0.524773057 -0.861084629
[51] -1.278417690 -1.035356133 -0.391810285 -1.223871063 -0.887715209
[56] -1.538472943  0.608542124  1.242268261  1.400596178 -1.182688470
[61] -0.506721241 -0.445167998  0.855105700 -0.164475696 -1.023157661
[66]  0.059864789  0.309980994 -0.768567987 -0.871515383  0.148153800
[71]  0.186071053  1.501123069 -0.085716739 -0.719699747 -0.997590487
attr(,"internals")
               Gi      E(Gi)        V(Gi)        Z(Gi) Pr(z != E(Gi))
 [1,] 0.155780489 0.16216216 0.0010065021 -0.201153316    0.840578694
 [2,] 0.195627717 0.13513514 0.0012099317  1.739088527    0.082019192
 [3,] 0.177431173 0.17567568 0.0014791768  0.045644666    0.963593468
 [4,] 0.188279871 0.18918919 0.0015710789 -0.022941247    0.981697139
 [5,] 0.161499316 0.16216216 0.0013873501 -0.017795896    0.985801679
 [6,] 0.148400521 0.13513514 0.0011700511  0.387808639    0.698157652
 [7,] 0.061984228 0.12162162 0.0010651910 -1.827279180    0.067657804
 [8,] 0.035096593 0.08108108 0.0007468681 -1.682632988    0.092446162
 [9,] 0.132741342 0.10810811 0.0009683907  0.791582358    0.428604237
[10,] 0.163766959 0.08108108 0.0007401762  3.039231470    0.002371825
[11,] 0.073377465 0.04054054 0.0004038391  1.634023502    0.102253916
[12,] 0.104628913 0.06756757 0.0006446180  1.459721351    0.144366672
[13,] 0.010581910 0.01351351 0.0001337885 -0.253452096    0.799918875
[14,] 0.218083224 0.12162162 0.0011072405  2.898901739    0.003744722
[15,] 0.098135674 0.08108108 0.0007648780  0.616659283    0.537459483
[16,] 0.159373006 0.12162162 0.0010909767  1.142944501    0.253061635
[17,] 0.040144764 0.04054054 0.0003981327 -0.019835157    0.984174872
[18,] 0.018672717 0.01351351 0.0001383932  0.438556285    0.660983078
[19,] 0.043312851 0.02702703 0.0002728197  0.985988570    0.324138722
[20,] 0.042530759 0.02702703 0.0002716130  0.940721263    0.346847719
[21,] 0.055354024 0.02702703 0.0002735385  1.712739354    0.086760502
[22,] 0.038267241 0.02702703 0.0002660885  0.689067156    0.490781007
[23,] 0.042675233 0.04054054 0.0004019491  0.106475550    0.915205054
[24,] 0.037353608 0.02702703 0.0002731428  0.624829738    0.532082811
[25,] 0.084413392 0.05405405 0.0005262380  1.323430679    0.185692195
[26,] 0.067241037 0.05405405 0.0005087178  0.584664818    0.558773115
[27,] 0.030769918 0.04054054 0.0004038953 -0.486169659    0.626846881
[28,] 0.025562276 0.04054054 0.0004026450 -0.746449363    0.455396010
[29,] 0.002395436 0.01351351 0.0001358688 -0.953827643    0.340170894
[30,] 0.018986841 0.02702703 0.0002712984 -0.488137883    0.625452180
[31,] 0.055875619 0.04054054 0.0003952383  0.771358900    0.440494229
[32,] 0.063961508 0.06756757 0.0006510467 -0.141327546    0.887611190
[33,] 0.046182728 0.05405405 0.0005260504 -0.343189680    0.731455768
[34,] 0.039979770 0.04054054 0.0003957117 -0.028190065    0.977510561
[35,] 0.022507680 0.02702703 0.0002689884 -0.275555366    0.782889596
[36,] 0.067689860 0.06756757 0.0006493753  0.004799014    0.996170956
[37,] 0.030685873 0.04054054 0.0003962793 -0.495041124    0.620571092
[38,] 0.052891016 0.02702703 0.0002702099  1.573420726    0.115621431
[39,] 0.063495045 0.04054054 0.0004019247  1.144973857    0.252219987
[40,] 0.025035630 0.04054054 0.0003927749 -0.782343385    0.434012796
[41,] 0.037199102 0.05405405 0.0005263816 -0.734644388    0.462556097
[42,] 0.024810696 0.02702703 0.0002696019 -0.134981141    0.892626785
[43,] 0.036344659 0.02702703 0.0002696202  0.567452280    0.570406939
[44,] 0.011651978 0.01351351 0.0001386454 -0.158095152    0.874381821
[45,] 0.037141798 0.01351351 0.0001324568  2.053028860    0.040069779
[46,] 0.023706884 0.06756757 0.0006358724 -1.739363723    0.081970805
[47,] 0.039917532 0.08108108 0.0007457988 -1.507307891    0.131731756
[48,] 0.027401858 0.06756757 0.0006386460 -1.589371187    0.111976616
[49,] 0.007406517 0.01351351 0.0001354292 -0.524773057    0.599740963
[50,] 0.034567597 0.05405405 0.0005121228 -0.861084629    0.389191434
[51,] 0.024931355 0.05405405 0.0005189407 -1.278417690    0.201102190
[52,] 0.030567377 0.05405405 0.0005145927 -1.035356133    0.300502624
[53,] 0.032737449 0.04054054 0.0003966265 -0.391810285    0.695198395
[54,] 0.036287368 0.06756757 0.0006532324 -1.223871063    0.221000871
[55,] 0.012461361 0.02702703 0.0002692238 -0.887715209    0.374693963
[56,] 0.070904195 0.12162162 0.0010867626 -1.538472943    0.123933019
[57,] 0.156262433 0.13513514 0.0012053318  0.608542124    0.542827977
[58,] 0.162052177 0.12162162 0.0010592260  1.242268261    0.214137601
[59,] 0.151497684 0.10810811 0.0009597208  1.400596178    0.161334865
[60,] 0.027117011 0.05405405 0.0005187512 -1.182688470    0.236932636
[61,] 0.007644482 0.01351351 0.0001341512 -0.506721241    0.612350424
[62,] 0.043933773 0.05405405 0.0005168176 -0.445167998    0.656198352
[63,] 0.089045218 0.06756757 0.0006308614  0.855105700    0.392492634
[64,] 0.037280662 0.04054054 0.0003928251 -0.164475696    0.869356678
[65,] 0.010270475 0.02702703 0.0002682157 -1.023157661    0.306233307
[66,] 0.055434688 0.05405405 0.0005318809  0.059864789    0.952263324
[67,] 0.032062885 0.02702703 0.0002639228  0.309980994    0.756575409
[68,] 0.004567282 0.01351351 0.0001354926 -0.768567987    0.442149816
[69,] 0.023036025 0.04054054 0.0004034132 -0.871515383    0.383472810
[70,] 0.043493135 0.04054054 0.0003971752  0.148153800    0.882221391
[71,] 0.058306639 0.05405405 0.0005223341  0.186071053    0.852389042
[72,] 0.088064305 0.05405405 0.0005133187  1.501123069    0.133323733
[73,] 0.038836696 0.04054054 0.0003951194 -0.085716739    0.931691595
[74,] 0.015378977 0.02702703 0.0002619412 -0.719699747    0.471709882
[75,] 0.010739893 0.02702703 0.0002665537 -0.997590487    0.318477976
attr(,"cluster")
 [1] High High Low  Low  Low  Low  Low  Low  Low  High High Low  Low  High Low 
[16] Low  Low  High High High High High High High Low  Low  High High Low  High
[31] Low  High Low  Low  Low  High High Low  High Low  Low  Low  Low  High Low 
[46] Low  Low  Low  Low  Low  Low  Low  Low  High Low  Low  High Low  Low  Low 
[61] Low  High Low  Low  Low  High Low  Low  High Low  Low  Low  Low  Low  Low 
Levels: Low High
attr(,"gstari")
[1] FALSE
attr(,"call")
localG(x = thailand$total_cases, listw = wm_d111000_lw)
attr(,"class")
[1] "localG"</code></pre>
</div>
</div>
<p>Now, we join the Gi values to the thailand sf data frame</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>thailand.gi <span class="ot">&lt;-</span> <span class="fu">cbind</span>(thailand, <span class="fu">as.matrix</span>(gi.fixed)) <span class="sc">%&gt;%</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_fixed =</span> as.matrix.gi.fixed.)</span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the threshold for hotspot areas (e.g., top 5% of Gi scores)</span></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fu">quantile</span>(thailand.gi<span class="sc">$</span>gstat_fixed, <span class="fl">0.95</span>)  </span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>hotspots <span class="ot">&lt;-</span> thailand.gi <span class="sc">%&gt;%</span></span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gstat_fixed <span class="sc">&gt;=</span> threshold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>hotspots_province_gstatscore <span class="ot">&lt;-</span> hotspots <span class="sc">%&gt;%</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM1_EN, gstat_fixed) <span class="sc">%&gt;%</span></span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(gstat_fixed))</span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(hotspots_province_gstatscore)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 4 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 325178.8 ymin: 1383501 xmax: 823915.5 ymax: 2191321
Projected CRS: WGS 84 / UTM zone 47N
       ADM1_EN gstat_fixed                       geometry
1    chon buri    3.039231 MULTIPOLYGON (((714273.8 13...
2 chachoengsao    2.898902 MULTIPOLYGON (((722656.1 15...
3 mae hong son    2.053029 MULTIPOLYGON (((401452.7 21...
4 samut prakan    1.739089 MULTIPOLYGON (((687139.8 15...</code></pre>
</div>
</div>
<section id="plotting-and-mapping-gi-values-with-fixed-distance-weights" class="level4">
<h4 class="anchored" data-anchor-id="plotting-and-mapping-gi-values-with-fixed-distance-weights">Plotting and Mapping Gi values with fixed distance weights</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>gi_total_cases <span class="ot">&lt;-</span> <span class="fu">qtm</span>(thailand, <span class="st">"total_cases"</span>)</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>Gimap <span class="ot">&lt;-</span><span class="fu">tm_shape</span>(thailand.gi) <span class="sc">+</span></span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"gstat_fixed"</span>, </span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-RdBu"</span>,</span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Gi"</span>) <span class="sc">+</span></span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb130-9"><a href="#cb130-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(hotspots) <span class="sc">+</span> </span>
<span id="cb130-10"><a href="#cb130-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"ADM1_EN"</span>, <span class="at">size =</span> <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">"black"</span>)</span>
<span id="cb130-11"><a href="#cb130-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-12"><a href="#cb130-12" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(gi_total_cases, Gimap, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "gstat_fixed" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>What can we infer from this plot?</p>
<ul>
<li><p>There are two hotspots (red), with one hotspot found around the center of thailand comprising of 3 provinces (chon buri , chachoengsao, samut prakan) and another hotspot found near the north-west area of thailand (mae hong son), accounting for the top 5% of gstat_fixed scores.</p></li>
<li><p>Although, outside the scope of this take-home exercise 2, it can be greatly inferred that there is one huge coldspot and a small cold spot that are situated near the center but more towards the north-west area.</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="gi-statistics-for-adaptive-distance" class="level3">
<h3 class="anchored" data-anchor-id="gi-statistics-for-adaptive-distance">7.3.2 Gi statistics for adaptive distance</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(thailand<span class="sc">$</span>ADM1_EN)</span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>gi.adaptive <span class="ot">&lt;-</span> <span class="fu">localG</span>(thailand<span class="sc">$</span>total_cases, knn8_lw)</span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>thailand.gi <span class="ot">&lt;-</span> <span class="fu">cbind</span>(thailand, <span class="fu">as.matrix</span>(gi.adaptive)) <span class="sc">%&gt;%</span></span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_adaptive =</span> as.matrix.gi.adaptive.)</span>
<span id="cb132-5"><a href="#cb132-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-6"><a href="#cb132-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the threshold for hotspot areas (e.g., top 5% of Gi scores)</span></span>
<span id="cb132-7"><a href="#cb132-7" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fu">quantile</span>(thailand.gi<span class="sc">$</span>gstat_adaptive, <span class="fl">0.95</span>)  </span>
<span id="cb132-8"><a href="#cb132-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-9"><a href="#cb132-9" aria-hidden="true" tabindex="-1"></a>hotspots <span class="ot">&lt;-</span> thailand.gi <span class="sc">%&gt;%</span></span>
<span id="cb132-10"><a href="#cb132-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gstat_adaptive <span class="sc">&gt;=</span> threshold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>hotspots_province_gstatscore <span class="ot">&lt;-</span> hotspots <span class="sc">%&gt;%</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM1_EN, gstat_adaptive) <span class="sc">%&gt;%</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(gstat_adaptive))</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(hotspots_province_gstatscore)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 4 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 656299 ymin: 1383501 xmax: 823915.5 ymax: 1546103
Projected CRS: WGS 84 / UTM zone 47N
       ADM1_EN gstat_adaptive                       geometry
1 chachoengsao       3.139752 MULTIPOLYGON (((722656.1 15...
2       rayong       2.688892 MULTIPOLYGON (((765405.7 13...
3    chon buri       2.499318 MULTIPOLYGON (((714273.8 13...
4 samut prakan       2.375555 MULTIPOLYGON (((687139.8 15...</code></pre>
</div>
</div>
<section id="plotting-and-mapping-gi-values-with-adaptive-distance-weights" class="level4">
<h4 class="anchored" data-anchor-id="plotting-and-mapping-gi-values-with-adaptive-distance-weights">Plotting and Mapping Gi values with adaptive distance weights</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>gi_total_cases<span class="ot">&lt;-</span> <span class="fu">qtm</span>(thailand, <span class="st">"total_cases"</span>)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>Gimap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(thailand.gi) <span class="sc">+</span> </span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"gstat_adaptive"</span>, </span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>, </span>
<span id="cb135-6"><a href="#cb135-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-RdBu"</span>, </span>
<span id="cb135-7"><a href="#cb135-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Gi"</span>) <span class="sc">+</span> </span>
<span id="cb135-8"><a href="#cb135-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb135-9"><a href="#cb135-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(hotspots) <span class="sc">+</span> </span>
<span id="cb135-10"><a href="#cb135-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"ADM1_EN"</span>, <span class="at">size =</span> <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">"black"</span>)</span>
<span id="cb135-11"><a href="#cb135-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-12"><a href="#cb135-12" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(gi_total_cases, Gimap, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "gstat_adaptive" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_Ex02_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Similarly, what inference can we draw from the adaptive-based plot?</p>
<ul>
<li><p>There are two hotspots (red), with both hotspots found around the center of thailand comprising of 4 provinces (chon buri , chachoengsao, samut prakan, and rayong), with about gstat_adaptive score of about 2.37 to 3.14.</p></li>
<li><p>Although, outside the scope of this take-home exercise 2, it can be greatly inferred that there is one huge coldspot situated near the north-west area.</p></li>
</ul></li>
</ul>
<hr>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">9.0 Conclusion</h2>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>